### DISCUSSION TITLE
Init command supports Env Vars?

### DISCUSSION THREAD

**Discussion by kun432** [microsoft/graphrag#1083] [Q&A]
I don't know how to use Env Vars in Indexing phase.
https://microsoft.github.io/graphrag/posts/config/env_vars/

Let's say we set an Env Var `GRAPHRAG_LLM_MODEL` like this:

```
export GRAPHRAG_LLM_MODEL=gpt-4o
```

Then, execute Init command:

```
python -m graphrag.index --init --root ./ragtest
```

settings.yaml is generated like this:

```
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4-turbo-preview
(snip)
```

Is this expected behaviour?
