### DISCUSSION TITLE
Can we incrementally add new documents to index?

### DISCUSSION THREAD

**Discussion by kavhad** [microsoft/graphrag#354] [Q&A] [answered]
With standard or baseline RAG it's simple to add new documents to the index as each document is unrelated, but since this is not the case for GraphRAG I assume a complete rebuild of the index is required or is their a feature for partial rebuild of the index based on what parts of the knowledge graph have changed?

**Comment by bmaltais** [comment, marked as answer]
Yes, you can. Just add the new document to the input folder and re-run the process. Only the new document will get entities created for it then it will be added to the summaries... That part will take some time unfortunatly... much more than I like ;-)

**Reply by mraguth** [reply]
But it supports only .txt files. Is it right?

**Reply by GaryDean** [reply]
From `setting.yaml` it seems as though you can specify the file pattern.  So it should support files with .md extensions and other text formats.  

```yaml
input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"
```
