### DISCUSSION TITLE
RuntimeError: Failed to generate valid JSON output

### DISCUSSION THREAD

**Discussion by micnikolaev** [microsoft/graphrag#463] [General]
I got "RuntimeError: Failed to generate valid JSON output" when tried to do  `python -m graphrag.query --root ./ragtest --method global "What is the release date of the book?"`

My config:
[settings.txt](https://github.com/user-attachments/files/16145861/settings.txt)

Logs:
[logs.json](https://github.com/user-attachments/files/16145867/logs.json)

**Comment by tingwei161803** [comment]
I got this error in the create_final_community_reports process

**Reply by brickfrog** [reply]
I also got this.  Was curious if there was any hardware, etc. that wasn't supported.

**Reply by micnikolaev** [reply]
on which OS do you run?

**Reply by tingwei161803** [reply]
I run with Ollama and succeeded with Gemma2-9b, but failed with Llama3-8b. I made the following modifications in setting.yaml:

```
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ollama
  type: openai_chat # or azure_openai_chat
  model: llama3
  model_supports_json: true # recommended if this is available for your model.
  request_timeout: 100000
  api_base: http://localhost:11434/v1

embeddings:
  async_mode: threaded # or asyncio
  llm:
    api_key: ollama
    type: openai_embedding # or azure_openai_embedding
    model: nomic_embed_text
    api_base: http://localhost:11434/api
```
