### ISSUE TITLE
[Bug]: <title>openai.NotFoundError: Error code: 404 - {'timestamp': '2024-08-23T08:47:30.562+00:00', 'status': 404, 'error': 'Not Found', 'path': '/v4/chat/completions/chat/completions'}

### ISSUE THREAD

**Issue by Egber1t** [microsoft/graphrag#1009]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

LLM：glm-4-0520    model: embedding-3

### GraphRAG Config Used

```yaml
# Paste your config here
  type: openai_chat # or azure_openai_chat
  model: glm-4-0520
  model_supports_json: False # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  api_base: https://open.bigmodel.cn/api/paas/v4/chat/completions



    model: embedding-3
    api_base: https://open.bigmodel.cn/api/paas/v4
```

### Logs and screenshots

不支持v4吗？

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:
