### ISSUE TITLE
[Bug]: Unable to ingest CSV file into Graph Rag

### ISSUE THREAD

**Issue by gregwilliam** [microsoft/graphrag#1011]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

I have a simple CSV file
[test.csv](https://github.com/user-attachments/files/16729088/test.csv) which I have written myself with a 'text' column added as per the suggestion in https://github.com/microsoft/graphrag/issues/588

when I execute GraphRag ingestion, the following error is generated

`running command:  python -m graphrag.index --root ./graphraghome
Virtual environment .venv is activated.
Exception in thread Thread-1 (_readerthread):
Traceback (most recent call last):
  File "C:\Users\GregWilliams\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1052, in _bootstrap_inner
    self.run()
  File "C:\Users\GregWilliams\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 989, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\GregWilliams\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
  File "C:\Users\GregWilliams\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 548: character maps to <undefined>
None`

This terminates the graph rag process, with only stats.json file generated in artefacts and reports containing the logs.json and indexing-engine.log

### Steps to reproduce

1) Install graph rag onto a standard VS Code project and set up as per 'getting started' guide (one exception rename ./graphragtest to ./graphraghome
2) set up connection to blob source. output, reporting as per attached yaml file, upload test.csv to blob storage
3) execute 'python -m graphrag.index --root ./graphraghome' on command line

### Expected Behavior

The GraphRag process should have completed, with the full range of 15 artifacts being created, insead the 1 artifact is created

### GraphRAG Config Used

```

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${OPENAI_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4o-mini
  model_supports_json: true # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  # api_base: https://<instance>.openai.azure.com
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  # top_p: 1 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: ${OPENAI_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-small
    # api_base: https://<instance>.openai.azure.com
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional
  


chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
input:
  type: blob
  connection_string: DefaultEndpointsProtocol=<redacted>
  container_name: <redacted>
  file_type: csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.csv$"

cache:
  type: blob
  base_dir: "cache"
  connection_string: <redacted>
  container_name: <redacted>

storage:
  type: blob
  base_dir: "output/${timestamp}/artifacts"
  connection_string: <redacted>
  container_name:<redacted>

reporting:
  type: blob
  base_dir: "output/${timestamp}/reports"
  connection_string: <redacted>
  container_name: <redacted>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

```

### Logs and screenshots

The log file is attached
[2024-08-23-12_49_56_897391.logs.json](https://github.com/user-attachments/files/16729126/2024-08-23-12_49_56_897391.logs.json)

The indexing engine log is attached: 
[indexing-engine (5).log](https://github.com/user-attachments/files/16729250/indexing-engine.5.log)

### Additional Information

- GraphRAG Version: graphrag==0.3.0
- Operating System: Win 11 Enterprise
- Python Version: 3.12.0
- Related Issues: possibly #588
