### ISSUE TITLE
[Issue]: Dependency Conflict: Streamlit (latest: v1.37.1) requires Tenacity <9, but graphrag depends on Tenacity v9.0

### ISSUE THREAD

**Issue by hamzaben86** [microsoft/graphrag#1030]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

When trying to add Streamlit (1.37.1) to a project that uses Tenacity 9.0.0, there's a version conflict. Streamlit requires Tenacity to be less than version 9, but graphrag depends on Tenacity version 9. This prevents users from using the latest versions of both libraries together.

### Steps to reproduce

1. Create a new Python project
2. Add Tenacity with version ^9.0.0 to the project dependencies
3. Attempt to add Streamlit to the project
4. Observe the error message indicating version incompatibility

### GraphRAG Config Used

```yaml
Python version: 3.11.0
Streamlit version: 1.37.1 (latest as of this report)
Tenacity version: 9.0.0
Operating System: Windows 11
Package manager: Poetry (but issue likely affects other package managers as well)
```

### Logs and screenshots

Using version ^1.37.1 for streamlit
Updating dependencies
Resolving dependencies... (0.3s)
Because no versions of streamlit match >1.37.1,<2.0.0
 and streamlit (1.37.1) depends on tenacity (>=8.1.0,<9), streamlit (>=1.37.1,<2.0.0) requires tenacity (>=8.1.0,<9).
So, because graphrag depends on both tenacity (^9.0.0) and streamlit (^1.37.1), version solving failed.

### Additional Information

- GraphRAG Version: 0.3.1
- Operating System: Win 11
- Python Version: 3.11.0
