### ISSUE TITLE
[Bug]: `run_extract_entities` fails on long input

### ISSUE THREAD

**Issue by isaac-pocketfm** [microsoft/graphrag#1239]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

When running the `create_base_extracted_entities` workflow on a large input file, in the `run_extract_entities` function, the call to `text_splitter.split_text` results in `text_list` having a different number of elements than `docs`. This means that the document indices in the results returned by the `extractor` do not align with the `docs` array, causing incorrect assignment of entities to docs, and potentially throwing an `IndexError`.

### Steps to reproduce

Run `run_pipeline_with_config` with the following config:
```yaml
workflows:
  - name: "create_base_extracted_entities"
    config:
      entity_extract:
          strategy: 
              type: graph_intelligence
              llm:
                type: openai_chat
                api_key: !ENV ${OPENAI_API_KEY}
                model: gpt-3.5-turbo
                temperature: 1.0
```
and with a target text file long enough that it is split into multiple chunks by the default `text_splitter`.

### Expected Behavior

Entity extraction should complete successfully.

### GraphRAG Config Used

```yaml
workflows:
  - name: "create_base_extracted_entities"
    config:
      entity_extract:
          strategy: 
              type: graph_intelligence
              llm:
                type: openai_chat
                api_key: !ENV ${OPENAI_API_KEY}
                model: gpt-3.5-turbo
                temperature: 1.0
```

### Logs and screenshots

```
  File "/Users/isaac/Library/Caches/pypoetry/virtualenvs/kb-proto-iXOcYfEQ-py3.12/lib/python3.12/site-packages/graphrag/index/verbs/entities/extraction/strategies/graph_intelligence/run_graph_intelligence.py", line 103, in <genexpr>
    docs[int(id)].id for id in node["source_id"].split(",")
    ~~~~^^^^^^^^^
IndexError: list index out of range
```

### Additional Information

- GraphRAG Version: 3.6
- Operating System: Mac OS
- Python Version: 3.12
- Related Issues:
