### ISSUE TITLE
[Bug]: <v0.4.0 bug when exec create_final_community_reports>using v0.4.0 to index, find "create_final_community_reports" raise error

### ISSUE THREAD

**Issue by rongekuta** [microsoft/graphrag#1384]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

i use cmd:
 time python -m graphrag index --root ./heishenhua-llama

to build graph index, but failed,  error message is as follows：

❌ create_final_community_reports
None
⠸ GraphRAG Indexer
├── Loading Input (text) - 3 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_entity_graph
├── create_final_entities
├── create_final_nodes
├── create_final_relationships
├── create_final_text_units
❌ Errors occurred during the pipeline run, see logs for more details.

stack trace is：

21:18:50,359 graphrag.utils.storage INFO read table from storage: create_final_nodes.parquet
21:18:50,369 graphrag.index.run.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/graphrag/index/run/run.py", line 269, in run_pipeline
    result = await _process_workflow(
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/graphrag/index/run/workflow.py", line 105, in _process_workflow
    result = await workflow.run(context, callbacks)
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 385, in run
    assert_all_visited()
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 358, in assert_all_visited
    raise NodeNotVisitedError(node_id, verb_name, missing_inputs)
datashaper.errors.NodeNotVisitedError: create_final_community_reports node not visited: name='30db20ba-26e5-44a5-9451-cce2e8111168', inputs=workflow:create_final_communities
21:18:50,370 graphrag.callbacks.file_workflow_callbacks INFO Error running pipeline! details=None
21:18:50,386 graphrag.cli.index ERROR Errors occurred during the pipeline run, see logs for more details.            

PS:
and i want config skip_workflows to skip create_final_community_reports
find  "skip_workflows" is not work in version 0.4.0 

### Steps to reproduce

time python -m graphrag index --root ./heishenhua-gpt4o-mini/

### GraphRAG Config Used

```yaml
# Paste your config here

encoding_model: cl100k_base
skip_workflows: [create_final_communities,create_final_community_reports,create_final_documents]
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: gpt-4o-mini
  model_supports_json: true # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  api_base: "sorry, not allowed to show"
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  tokens_per_minute: 100_000 # set a leaky bucket throttle
  requests_per_minute: 100 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  concurrent_requests: 1 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  # top_p: 1 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  # target: required # or all
  # batch_size: 16 # the number of documents to send in a single request
  # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-small
    api_base: "sorry, not allowed to show"
    # api_base: https://<instance>.openai.azure.com
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    tokens_per_minute: 100_000 # set a leaky bucket throttle
    requests_per_minute: 100 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    concurrent_requests: 1 # the number of parallel inflight requests that may be made

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  type: file # or blob
  base_dir: "output"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## strategy: fully override the entity extraction strategy.
  ##   type: one of graph_intelligence, graph_intelligence_json and nltk
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [game,organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

```

### Logs and screenshots

23:44:35,272 graphrag.index.run.workflow INFO dependencies for create_final_entities: ['create_base_entity_graph']
23:44:35,275 graphrag.index.run.workflow WARNING Dependency table create_base_entity_graph not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
23:44:35,280 datashaper.workflow.workflow INFO executing verb create_final_entities
23:44:35,335 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_entities.parquet
23:44:35,514 graphrag.index.run.workflow INFO dependencies for create_final_nodes: ['create_base_entity_graph']
23:44:35,515 graphrag.index.run.workflow WARNING Dependency table create_base_entity_graph not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
23:44:35,521 datashaper.workflow.workflow INFO executing verb create_final_nodes
23:44:35,741 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_nodes.parquet
23:44:35,905 graphrag.index.run.workflow INFO dependencies for create_final_relationships: ['create_base_entity_graph', 'create_final_nodes']
23:44:35,906 graphrag.index.run.workflow WARNING Dependency table create_base_entity_graph not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
23:44:35,907 graphrag.utils.storage INFO read table from storage: create_final_nodes.parquet
23:44:35,946 datashaper.workflow.workflow INFO executing verb create_final_relationships
23:44:36,1 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_relationships.parquet
23:44:36,177 graphrag.index.run.workflow INFO dependencies for create_final_text_units: ['create_final_relationships', 'create_final_entities', 'create_base_text_units']
23:44:36,177 graphrag.utils.storage INFO read table from storage: create_final_relationships.parquet
23:44:36,182 graphrag.utils.storage INFO read table from storage: create_final_entities.parquet
23:44:36,187 graphrag.index.run.workflow WARNING Dependency table create_base_text_units not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
23:44:36,196 datashaper.workflow.workflow INFO executing verb create_final_text_units
23:44:36,222 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_text_units.parquet
23:44:36,409 graphrag.index.run.workflow INFO dependencies for create_final_community_reports: ['create_final_relationships', 'create_final_nodes']
23:44:36,410 graphrag.utils.storage INFO read table from storage: create_final_relationships.parquet
23:44:36,416 graphrag.utils.storage INFO read table from storage: create_final_nodes.parquet
23:44:36,428 graphrag.index.run.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/graphrag/index/run/run.py", line 269, in run_pipeline
    result = await _process_workflow(
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/graphrag/index/run/workflow.py", line 105, in _process_workflow
    result = await workflow.run(context, callbacks)
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 385, in run
    assert_all_visited()
  File "/root/miniconda3/envs/graphrag-v0.4.0/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 358, in assert_all_visited
    raise NodeNotVisitedError(node_id, verb_name, missing_inputs)
datashaper.errors.NodeNotVisitedError: create_final_community_reports node not visited: name='31c03cf7-01cc-4cdd-9c27-d2c5d93e2b9b', inputs=workflow:create_final_communities
23:44:36,429 graphrag.callbacks.file_workflow_callbacks INFO Error running pipeline! details=None
23:44:36,449 graphrag.cli.index ERROR Errors occurred during the pipeline run, see logs for more details.

### Additional Information

- GraphRAG Version:0.4.0
- Operating System:ubuntu
- Python Version: 3.10.15
- Related Issues:
