### ISSUE TITLE
[Bug]: <title> Error generate_text_embeddings

### ISSUE THREAD

**Issue by LuWei6896** [microsoft/graphrag#1472]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

![Image](https://github.com/user-attachments/assets/44670764-173f-47bb-bf74-a25147db3234)

### Expected Behavior

i use ollama
![Image](https://github.com/user-attachments/assets/190cfdc5-cb4f-4685-80a9-d6ce051db4ad)

### GraphRAG Config Used

```yaml
### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.

encoding_model: cl100k_base # this needs to be matched to your model!

llm:
  api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
  type: openai_chat # or azure_openai_chat
  model: qwen2.5:7b
  model_supports_json: true # recommended if this is available for your model.
  # audience: "https://cognitiveservices.azure.com/.default"
  request_timeout: 2000.0
  api_base: http://xxxx:11434/v1/
  max_tokens : 2048
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>

parallelization:
  stagger: 0.1
  num_threads: 200

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store:
    type: lancedb
    db_uri: 'output\lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: all-minilm:latest
    api_base: http://xxxx:11434/api/embeddings
    batch_max_tokens: 2048
    # api_version: 2024-02-15-preview
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>

### Input settings ###

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

cache:
  type: file # or blob
  base_dir: "cache/${timestamp}"

reporting:
  type: file # or console, blob
  base_dir: "logs/${timestamp}"

storage:
  type: file # or blob
  base_dir: "output/${timestamp}"

## only turn this on if running `graphrag index` with custom settings
## we normally use `graphrag update` with the defaults
update_index_storage:
  # type: file # or blob
  # base_dir: "update_output"

### Workflow settings ###

skip_workflows: []

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [drug,clinical trial,target]
  max_gleanings: 1

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  enabled: false
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 30

embed_graph:
  enabled: true # if true, will generate node2vec embeddings for nodes

umap:
  enabled: true # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false
  embeddings: false
  transient: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  prompt: "prompts/drift_search_system_prompt.txt"


```

### Logs and screenshots

{
    "type": "error",
    "data": "Error Invoking LLM",
    "stack": "Traceback (most recent call last):\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.InternalServerError: Error code: 500 - {'error': {'message': 'an error was encountered while running the model: unexpected EOF', 'type': 'api_error', 'param': None, 'code': None}}\n",
    "source": "Error code: 500 - {'error': {'message': 'an error was encountered while running the model: unexpected EOF', 'type': 'api_error', 'param': None, 'code': None}}",
    "details": {
        "input": "-Goal-\r\n\r\nGiven a text document that is potentially relevant to this activity and a list of entity types, identify all entities of those types from the text and all relationships among the identified entities, then filter them based on the community list (drug, clinical trial, target, indication, pharmaceutical company, medical institution, organization, literature, market, process, personnel, doctor, researcher, patient, chemical molecule, biological protein, biological gene, treatment technology). Only entities belonging to the specified communities should be retained.\r\n\r\n-Steps-\r\n\r\n1. Identify all entities. For each identified entity, extract the following information:\r\n\r\nentity_name: Name of the entity, capitalized\r\nentity_type: One of the following types: [{drug, clinical trial, target, indication, pharmaceutical company, medical institution, organization, literature, market, process, personnel, doctor, researcher, patient, chemical molecule, biological protein, biological gene, treatment technology}]\r\nentity_description: Comprehensive description of the entity's attributes and activities.\r\nFormat each entity as:\r\n(\"entity\"\"⧫<entity_name>⧫<entity_type>⧫<entity_description>)\r\n\r\n2. Community filter: Only keep the entities that belong to the specified community list, and discard the others.\r\n\r\n3. From the entities identified in step 1、2,identify all pairs of (source_entity, target_entity) relationships. From the entities identified in Step 1、2, find relationships based on the following:\r\n\r\nsource_entity: name of the source entity, as identified in step 1、2\r\ntarget_entity: name of the target entity, as identified in step 1、2\r\nrelationship_description: Explanation as to why you think the source entity and the target entity are related to each other.\r\nrelationship_strength: A numeric score indicating the strength of the relationship between the source entity and the target entity.\r\nFormat each relationship as:\r\n(\"relationship\"⧫<source_entity>⧫<target_entity>⧫<relationship_description>⧫<relationship_strength>)\r\n\r\n4.Community filter: Ensure the relationship involves only entities belonging to the community list.\r\n\r\n5. Return output in English as a single list of all the entities and relationships identified in steps 1、2、3、4. Use ## as the list delimiter.\r\n\r\n6. When finished, output <|COMPLETE|>\r\n\r\n-Examples-\r\n######################\r\nExample 1:\r\nEntity_types:DRUG, PERSONNEL, PROCESS, TREATMENT TECHNOLOGY\r\nText:'''{{\r\n\"title\": \"核糖开关调节的嵌合抗原受体（RiboCAR）增强了CAR-T细胞抗癌效果\",\r\n\"author\": \"郭学翠，王乔治，钟赵静，张志凯，Samuel D Waksal，Alexandria J Forbes\",\r\n\"research_unit\": \"基因调控，MeiraGTx，纽约\",\r\n\"carrier_type\": \"未提供\",\r\n\"cell_type\": \"CAR-T\",\r\n\"process_stage\": \"生产\",\r\n\"method\": \"本研究开发了一种名为RiboCAR的系统，通过口服小分子诱导剂精确控制CAR表达。RiboCAR包含合成的哺乳动物ON核糖开关，其中的适配子作为特定新型小分子诱导剂的传感器。\",\r\n\"result\": \"在没有小分子的情况下，CAR基因的表达水平被精确控制，且无法检测到CAR。随着小分子剂量的增加，CAR的表达水平呈现出精确的剂量依赖性响应，并在最大小分子剂量下达到高于组成性活性CAR的水平。诱导的CAR表达在小分子撤回后会降低。RiboCAR-T细胞显示出比组成性CAR-T细胞更强的抗癌活性，具有更强的细胞毒性和较低水平的细胞因子释放，以及更高的体外肿瘤细胞刺激扩张能力。\",\r\n\"advantage\": \"核糖开关调节的CAR提供了严格控制的CAR-T细胞，除了潜在的安全益处外，还可能提高效力。\",\r\n\"file_link\": \"RiboCAR-T-Poster-21-Final-7_31_23.pdf\"\r\n}}'''\r\n######################\r\nOutput:\r\n(\"entity\"<|>RiboCAR<|>PROCESS<|>The RiboCAR system is a novel approach to controlling CAR-T cell therapy using an oral small molecule inducer to regulate CAR expression.\")\r\n##\r\n(\"entity\"<|>郭学翠<|>PERSONNEL<|>Guo Xuecui is an author of the study, contributing to the development of the RiboCAR system.\")\r\n##\r\n(\"entity\"<|>MeiraGTx<|>ORGANIZATION<|>MeiraGTx, located in New York, is the research unit behind the development of RiboCAR and its application in CAR-T cell therapy.\")\r\n##\r\n(\"entity\"<|>CAR-T<|>PROCESS<|>CAR-T cells are genetically modified immune cells used for cancer treatment, with RiboCAR improving their activation and potency through precise control of CAR expression.\")\r\n##\r\n(\"entity\"<|>RiboCAR-T细胞<|>TREATMENT TECHNOLOGY<|>RiboCAR-T cells are engineered with a synthetic riboswitch to regulate CAR expression, offering potential advantages in safety and efficacy.\")\r\n##\r\n(\"entity\"<|>Samuel D Waksal<|>PERSONNEL<|>Samuel D. Waksal is an author of the study, involved in the research of RiboCAR technology.\")\r\n##\r\n(\"relationship\"<|>郭学翠<|>MeiraGTx<|>Guo Xuecui is a researcher at MeiraGTx and co-authored the study on RiboCAR<|>9\")\r\n##\r\n(\"relationship\"<|>RiboCAR<|>CAR-T<|>RiboCAR is a process designed to enhance the effectiveness of CAR-T cells by controlling CAR expression with small molecule inducers<|>9\")\r\n<|COMPLETE|>\r\n\r\n######################\r\nExample 2:\r\nEntity_types: ORGANIZATION\r\nText:'''{{\r\n    \"title\": \"针对CD1a的人源化CAR-T细胞产品OC-1治疗复发/难治性T细胞急性淋巴细胞白血病的临床试验\",\r\n    \"author\": \"未提供\",\r\n    \"research_unit\": \"Instituto de Investigacion CONTRA LA LEUCEMIA，Josep Carreras Leukaemia Research Institute\",\r\n    \"carrier_type\": \"人源化CAR-T细胞产品\",\r\n    \"cell_type\": \"针对CD1a靶点\",\r\n    \"process_stage\": \"I期临床试验\",\r\n    \"method\": \"分阶段给药设计，包括不同的剂量递增队列\",\r\n    \"result\": \"计划入组12-20名患者\",\r\n    \"advantage\": \"安全性评估包括特别关注的副作用事件、不良事件发生率和免疫学稳态评估，有效性评估包括无进展生存期、缓解率、首次OC-1输注后的持续时间、微小残留病响应和总生存期\",\r\n    \"file_link\": \"IMG_4081.JPG\"\r\n}}'''\r\n######################\r\nOutput:\r\n(\"entity\"<|>Instituto de Investigacion CONTRA LA LEUCEMIA<|>ORGANIZATION<|>The Instituto de Investigacion CONTRA LA LEUCEMIA is involved in clinical research focused on treating relapsed/refractory T-cell acute lymphoblastic leukemia using OC-1 CAR-T cell therapy.\")\r\n##\r\n(\"entity\"<|>Josep Carreras Leukaemia Research Institute<|>ORGANIZATION<|>The Josep Carreras Leukaemia Research Institute is conducting a Phase I clinical trial of the humanized OC-1 CAR-T cell product targeting CD1a in T-cell acute lymphoblastic leukemia.\")\r\n##\r\n(\"relationship\"<|>Instituto de Investigacion CONTRA LA LEUCEMIA<|>Josep Carreras Leukaemia Research Institute<|>Instituto de Investigacion CONTRA LA LEUCEMIA collaborates with Josep Carreras Leukaemia Research Institute in researching CAR-T cell therapy for leukemia.<|>9\")\r\n<|COMPLETE|>\r\n\r\n######################\r\nExample 3:\r\nEntity_types: DRUG, CLINICAL TRIAL, TARGET, INDICATION, PHARMACEUTICAL COMPANY, MEDICAL INSTITUTION, ORGANIZATION, LITERATURE, MARKET, PROCESS, PERSONNEL, DOCTOR, RESEARCHER, PATIENT, CHEMICAL MOLECULE, BIOLOGICAL PROTEIN, BIOLOGICAL GENE, TREATMENT TECHNOLOGY\r\nText:'''{{\r\n    \"title\": \"新型多靶点抗癌药物AZ-123联合CRISPR-Cas9基因编辑技术的临床试验，治疗HER2阳性乳腺癌\",\r\n    \"author\": \"Dr. Emily Johnson, Dr. Michael Wang, 张晓峰, 刘敏\",\r\n    \"research_unit\": \"Harvard Medical School, 北京协和医院\",\r\n    \"drug\": \"AZ-123\",\r\n    \"clinical_trial\": \"III期临床试验\",\r\n    \"target\": \"HER2, BRCA1\",\r\n    \"indication\": \"HER2阳性乳腺癌\",\r\n    \"pharmaceutical_company\": \"Global Pharma Inc.\",\r\n    \"medical_institution\": \"北京协和医院\",\r\n    \"organization\": \"美国国家癌症研究所 (NCI)\",\r\n    \"literature\": \"《癌症研究进展杂志》第10期，2023年\",\r\n    \"market\": \"全球抗癌药物市场\",\r\n    \"process\": \"基于患者分层的个性化治疗\",\r\n    \"personnel\": \"张晓峰\",\r\n    \"doctor\": \"Dr. Emily Johnson\",\r\n    \"researcher\": \"Dr. Michael Wang\",\r\n    \"patient\": \"计划入组500名HER2阳性乳腺癌患者\",\r\n    \"chemical_molecule\": \"AZ-123活性分子\",\r\n    \"biological_protein\": \"HER2蛋白\",\r\n    \"biological_gene\": \"BRCA1基因\",\r\n    \"treatment_technology\": \"CRISPR-Cas9基因编辑技术\",\r\n    \"file_link\": \"Clinical_Trial_AZ123_Report.pdf\"\r\n}}'''\r\n######################\r\nOutput:\r\n(\"entity\"<|>AZ-123<|>DRUG<|>AZ-123 is a novel multi-target cancer drug being tested in combination with CRISPR-Cas9 for HER2-positive breast cancer.\")\r\n##\r\n(\"entity\"<|>III期临床试验<|>CLINICAL TRIAL<|>The Phase III clinical trial aims to evaluate the safety and efficacy of AZ-123 in HER2-positive breast cancer patients.\")\r\n##\r\n(\"entity\"<|>HER2, BRCA1<|>TARGET<|>HER2 and BRCA1 are key targets in the study of AZ-123 for HER2-positive breast cancer.\")\r\n##\r\n(\"entity\"<|>HER2阳性乳腺癌<|>INDICATION<|>HER2-positive breast cancer is the primary indication for the AZ-123 clinical trial.\")\r\n##\r\n(\"entity\"<|>Global Pharma Inc.<|>PHARMACEUTICAL COMPANY<|>Global Pharma Inc. is developing AZ-123 for cancer treatment.\")\r\n##\r\n(\"entity\"<|>北京协和医院<|>MEDICAL INSTITUTION<|>Peking Union Medical College Hospital is a key medical institution participating in the clinical trial.\")\r\n##\r\n(\"entity\"<|>美国国家癌症研究所 (NCI)<|>ORGANIZATION<|>The National Cancer Institute (NCI) is involved in the AZ-123 clinical trial.\")\r\n##\r\n(\"entity\"<|>《癌症研究进展杂志》第10期，2023年<|>LITERATURE<|>The Cancer Research Progress Journal, Issue 10, 2023, features research on AZ-123.\")\r\n##\r\n(\"entity\"<|>全球抗癌药物市场<|>MARKET<|>The global cancer drug market is expected to be impacted by the introduction of AZ-123.\")\r\n##\r\n(\"entity\"<|>基于患者分层的个性化治疗<|>PROCESS<|>A patient-stratified personalized treatment process is central to the AZ-123 clinical trial.\")\r\n##\r\n(\"entity\"<|>张晓峰<|>PERSONNEL<|>Zhang Xiaofeng is a key member involved in the clinical trial.\")\r\n##\r\n(\"entity\"<|>Dr. Emily Johnson<|>DOCTOR<|>Dr. Emily Johnson is leading the clinical trial at Peking Union Medical College Hospital.\")\r\n##\r\n(\"entity\"<|>Dr. Michael Wang<|>RESEARCHER<|>Dr. Michael Wang is conducting research on the AZ-123 drug and its genetic implications.\")\r\n##\r\n(\"entity\"<|>500名HER2阳性乳腺癌患者<|>PATIENT<|>The trial plans to enroll 500 patients with HER2-positive breast cancer.\")\r\n##\r\n(\"entity\"<|>AZ-123活性分子<|>CHEMICAL MOLECULE<|>AZ-123 active molecules are the core chemical component of the drug.\")\r\n##\r\n(\"entity\"<|>HER2蛋白<|>BIOLOGICAL PROTEIN<|>The HER2 protein is a biological target for AZ-123 in treating breast cancer.\")\r\n##\r\n(\"entity\"<|>BRCA1基因<|>BIOLOGICAL GENE<|>The BRCA1 gene is a genetic focus of the CRISPR-Cas9 editing process.\")\r\n##\r\n(\"entity\"<|>CRISPR-Cas9基因编辑技术<|>TREATMENT TECHNOLOGY<|>CRISPR-Cas9 gene editing technology is used to enhance the efficacy of AZ-123 in the trial.\")\r\n##\r\n(\"relationship\"<|>Dr. Emily Johnson<|>北京协和医院<|>Dr. Emily Johnson is leading the trial at Peking Union Medical College Hospital.<|>9\")\r\n##\r\n(\"relationship\"<|>AZ-123<|>Global Pharma Inc.<|>Global Pharma Inc. is the developer of AZ-123.<|>9\")\r\n<|COMPLETE|>\r\n\r\n######################\r\n-Real Data-\r\n######################\r\nEntity_types: drug,clinical trial,target,indication,pharmaceutical company,medical institution,organization,literature,market,process,personnel,doctor,researcher,patient,chemical molecule,biological protein,biological gene,treatment technology\r\nText: P0729: Targeting receptor tyrosine kinase ROR2 with CAR T cells is effective against hematologic and solid tumors, and well tolerated in mice.\nJ Weber(1) M Rade(2) P Spieler(1) F Freitag(1) M Rosenfeldt(4) C Kalogirou(3) K M Kortüm(6) H Einsele(5) T Nerreter(1) M Hudecek(1) \n1:Chair in Cellular Immunotherapy, University Hospital Wuerzburg; 2:Fraunhofer Institute for Cell Therapy and Immunology; 3:Department of Urology and Pediatric Urology, University Hospital Wuerzburg; 4:Institute of Pathology, Julius-Maximilians University Wuerzburg; 5:Medical Clinic and Policlinic II, University Hospital Wuerzburg; 6:Chair of Translational Myeloma Research, University Hospital Wuerzburg\nThe remarkable results obtained from autologous cell therapy of selected hematological malignancies using chimeric antigen receptor (CAR)-modified T cells has ignited a desire to expand this treatment approach to other diseases, including autoimmunity and solid cancers. However, CAR-T cell products have repeatedly failed to clear benchmarks of clinical efficacy in solid cancers. The development of CAR-T cell products targeting cross-entity tumor antigens expressed in both hematological and solid cancer represent a unique opportunity to study the underlying mechanisms in more detail and to engage in an iterative optimization approach to augment CAR-T cell performance.\nHere, we propose the receptor tyrosine kinase-like orphan receptor 2 (ROR2) as a novel target for CAR-T cell therapy with cross entity application in two representative hematological and solid cancers - multiple myeloma (MM) and clear cell renal cell carcinoma (ccRCC), respectively.\nWe studied the expression of ROR2 protein on the cell surface of MM cell lines and primary using flow cytometry and found ROR2 to be expressed in >90% of patient samples. Co-cultivation with a ROR2-specific CAR-T cell product (ROR2-CART) induced specific lysis of ROR2-positive tumor cell lines and primary samples, but failed to recognize ROR2-knockout control cell lines. In an orthotopic MM xenograft model (U266/NSG), treatment with ROR2-CART significantly reduced tumor burden, improved median overall survival (119 vs. 149 days, p=0.0039), and induced a long-tern curative effect in a subset of mice (25%; 3/12 mice). Importantly, treatment with ROR2-CART was well tolerated in mice, despite comparable gene expression levels and cross-reactivity of the cell product with murine Ror2. \nTo study the relevance of targeting ROR2 in solid cancers, screened the TCGA database and performed correlation analyses between ROR2 gene expression and clinical parameters for all 32 projects. Our analyses revealed a significant correlation between clinical parameters and ROR2 expression in six cancer entities including brain, kidney and stomach cancers. We selected ccRCC for further assessment, due to a strong correlation between ROR2 expression and disease-specific survival. Using qPCR, we confirmed ROR2 overexpression in ccRCC patient samples and cell lines, and quantified the expression of ROR2 on the cell surface using dSTORM microscopy.\nCo-cultivation with ROR2-CART induced antigen-specific antitumor reactivity against ROR2-positive ccRCC cell lines, but not ROR2-negative reference cells. Similarly, treatment with ROR2-CART significantly increased mOS in a xenograft model of ccRCC (52 vs. 84 days, p=0.0035). As expected, conventional ROR2-CART only elicited a temporary anti-tumor response and did not achieve complete tumor clearance, providing us with a platform to initiate iterative cell product optimization for solid cancers. In a first case study, we explored transcription factor modulation, as well as the combinatorial use of small molecule inhibitors. Our data show that both overexpression of cJUN and the use of the TKI cabozantinib can be used to augment the potency of ROR2-CART, both in vitro and in vivo.\nCollectively, these data show that ROR2 is a relevant target in various hematological and solid tumors. ROR2-positive hematological and solid cancers can be addressed effectively using ROR2-CART without adverse effects in preclinical models.\r\n######################\r\nOutput:\r\n\r\n"
    }
}
{
    "type": "error",
    "data": "Entity Extraction Error",
    "stack": "Traceback (most recent call last):\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 125, in __call__\n    result = await self._process_document(text, prompt_variables)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\index\\graph\\extractors\\graph\\graph_extractor.py\", line 153, in _process_document\n    response = await self._llm(\n               ^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\openai\\json_parsing_llm.py\", line 34, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_token_replacing_llm.py\", line 37, in __call__\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_history_tracking_llm.py\", line 33, in __call__\n    output = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\caching_llm.py\", line 96, in __call__\n    result = await self._delegate(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 177, in __call__\n    result, start = await execute_with_retry()\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 159, in execute_with_retry\n    async for attempt in retryer:\n  File \"D:\\librarys\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 166, in __anext__\n    do = await self.iter(retry_state=self._retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\tenacity\\asyncio\\__init__.py\", line 153, in iter\n    result = await action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\tenacity\\_utils.py\", line 99, in inner\n    return call(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\tenacity\\__init__.py\", line 418, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\tenacity\\__init__.py\", line 185, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\concurrent\\futures\\_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\concurrent\\futures\\_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 165, in execute_with_retry\n    return await do_attempt(), start\n           ^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\rate_limiting_llm.py\", line 147, in do_attempt\n    return await self._delegate(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 50, in __call__\n    return await self._invoke(input, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\base\\base_llm.py\", line 54, in _invoke\n    output = await self._execute_llm(input, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\graphrag\\llm\\openai\\openai_chat_llm.py\", line 53, in _execute_llm\n    completion = await self.client.chat.completions.create(\n                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\resources\\chat\\completions.py\", line 1661, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1839, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1533, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\librarys\\Lib\\site-packages\\openai\\_base_client.py\", line 1634, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.InternalServerError: Error code: 500 - {'error': {'message': 'an error was encountered while running the model: unexpected EOF', 'type': 'api_error', 'param': None, 'code': None}}\n",
    "source": "Error code: 500 - {'error': {'message': 'an error was encountered while running the model: unexpected EOF', 'type': 'api_error', 'param': None, 'code': None}}",
    "details": {
        "doc_index": 0,
        "text": "P0729: Targeting receptor tyrosine kinase ROR2 with CAR T cells is effective against hematologic and solid tumors, and well tolerated in mice.\nJ Weber(1) M Rade(2) P Spieler(1) F Freitag(1) M Rosenfeldt(4) C Kalogirou(3) K M Kortüm(6) H Einsele(5) T Nerreter(1) M Hudecek(1) \n1:Chair in Cellular Immunotherapy, University Hospital Wuerzburg; 2:Fraunhofer Institute for Cell Therapy and Immunology; 3:Department of Urology and Pediatric Urology, University Hospital Wuerzburg; 4:Institute of Pathology, Julius-Maximilians University Wuerzburg; 5:Medical Clinic and Policlinic II, University Hospital Wuerzburg; 6:Chair of Translational Myeloma Research, University Hospital Wuerzburg\nThe remarkable results obtained from autologous cell therapy of selected hematological malignancies using chimeric antigen receptor (CAR)-modified T cells has ignited a desire to expand this treatment approach to other diseases, including autoimmunity and solid cancers. However, CAR-T cell products have repeatedly failed to clear benchmarks of clinical efficacy in solid cancers. The development of CAR-T cell products targeting cross-entity tumor antigens expressed in both hematological and solid cancer represent a unique opportunity to study the underlying mechanisms in more detail and to engage in an iterative optimization approach to augment CAR-T cell performance.\nHere, we propose the receptor tyrosine kinase-like orphan receptor 2 (ROR2) as a novel target for CAR-T cell therapy with cross entity application in two representative hematological and solid cancers - multiple myeloma (MM) and clear cell renal cell carcinoma (ccRCC), respectively.\nWe studied the expression of ROR2 protein on the cell surface of MM cell lines and primary using flow cytometry and found ROR2 to be expressed in >90% of patient samples. Co-cultivation with a ROR2-specific CAR-T cell product (ROR2-CART) induced specific lysis of ROR2-positive tumor cell lines and primary samples, but failed to recognize ROR2-knockout control cell lines. In an orthotopic MM xenograft model (U266/NSG), treatment with ROR2-CART significantly reduced tumor burden, improved median overall survival (119 vs. 149 days, p=0.0039), and induced a long-tern curative effect in a subset of mice (25%; 3/12 mice). Importantly, treatment with ROR2-CART was well tolerated in mice, despite comparable gene expression levels and cross-reactivity of the cell product with murine Ror2. \nTo study the relevance of targeting ROR2 in solid cancers, screened the TCGA database and performed correlation analyses between ROR2 gene expression and clinical parameters for all 32 projects. Our analyses revealed a significant correlation between clinical parameters and ROR2 expression in six cancer entities including brain, kidney and stomach cancers. We selected ccRCC for further assessment, due to a strong correlation between ROR2 expression and disease-specific survival. Using qPCR, we confirmed ROR2 overexpression in ccRCC patient samples and cell lines, and quantified the expression of ROR2 on the cell surface using dSTORM microscopy.\nCo-cultivation with ROR2-CART induced antigen-specific antitumor reactivity against ROR2-positive ccRCC cell lines, but not ROR2-negative reference cells. Similarly, treatment with ROR2-CART significantly increased mOS in a xenograft model of ccRCC (52 vs. 84 days, p=0.0035). As expected, conventional ROR2-CART only elicited a temporary anti-tumor response and did not achieve complete tumor clearance, providing us with a platform to initiate iterative cell product optimization for solid cancers. In a first case study, we explored transcription factor modulation, as well as the combinatorial use of small molecule inhibitors. Our data show that both overexpression of cJUN and the use of the TKI cabozantinib can be used to augment the potency of ROR2-CART, both in vitro and in vivo.\nCollectively, these data show that ROR2 is a relevant target in various hematological and solid tumors. ROR2-positive hematological and solid cancers can be addressed effectively using ROR2-CART without adverse effects in preclinical models."
    }
}

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:
