### ISSUE TITLE
[Issue]: create_base_entity_graph Workflow Fails in GraphRAG Pipeline - ValueError: Columns must be same length as key

### ISSUE THREAD

**Issue by Adriansdls** [microsoft/graphrag#1476]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The create_base_entity_graph step in the indexing pipeline fails with the following error:

`ValueError: Columns must be same length as key

The error occurs during the clustering step when executing the pipeline, with all the .txt files I have tested. The workflow appears to fail due to mismatched DataFrame dimensions in the **cluster_graph** function.

During debugging, I found that certain workflows had empty outputs, causing subsequent steps to fail. Specifically, the create_base_text_units workflow returned an empty DataFrame. This likely caused downstream workflows like create_base_entity_graph to fail due to missing nodes, as indicated by errors such as "Graph has no nodes" and "ValueError: Columns must be same length as key."

The document processing step (create_final_documents) was successful, and the output was saved to disk. However, the lack of valid inputs from earlier steps, particularly the entity_extraction process, prevented further workflows from completing successfully. The root cause appears to be the empty output from the create_base_text_units step, which cascaded into failures in subsequent processes.

Below is the entire log but first here some relevant lines
```
15:40:29,46 graphrag.index.run.workflow WARNING Dependency table create_base_text_units not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.

``` 
```
15:42:13,262 graphrag.index.operations.cluster_graph WARNING Graph has no nodes
15:42:13,266 datashaper.workflow.workflow ERROR Error executing verb "create_base_entity_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py", line 51, in create_base_entity_graph
    output = await create_base_entity_graph_flow(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/flows/create_base_entity_graph.py", line 77, in create_base_entity_graph
    clustered = cluster_graph(
                ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/operations/cluster_graph.py", line 90, in cluster_graph
    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)
    ~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
15:42:13,273 graphrag.callbacks.file_workflow_callbacks INFO Error executing verb "create_base_entity_graph" in create_base_entity_graph: Columns must be same length as key details=None
15:42:13,273 graphrag.index.run.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/run/run.py", line 274, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/run/workflow.py", line 108, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py", line 51, in create_base_entity_graph
    output = await create_base_entity_graph_flow(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/flows/create_base_entity_graph.py", line 77, in create_base_entity_graph
    clustered = cluster_graph(
                ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/operations/cluster_graph.py", line 90, in cluster_graph
    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)
    ~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
15:42:13,275 graphrag.callbacks.file_workflow_callbacks INFO Error running pipeline! details=None
15:42:13,283 graphrag.cli.index ERROR Errors occurred during the pipeline run, see logs for more details.

``` 

**Entire log**

```
15:40:28,15 graphrag.cli.index INFO Logging enabled at /Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline/logs/indexing-engine.log
15:40:28,17 graphrag.cli.index INFO Starting pipeline run for: 20241206-154028, dry_run=False
15:40:28,17 graphrag.cli.index INFO Using default configuration: {
    "llm": {
        "api_key": "==== REDACTED ====",
        "type": "openai_chat",
        "model": "gpt-4o",
        "max_tokens": 4000,
        "temperature": 0.0,
        "top_p": 1.0,
        "n": 1,
        "request_timeout": 180.0,
        "api_base": null,
        "api_version": null,
        "proxy": null,
        "audience": null,
        "deployment_name": null,
        "model_supports_json": true,
        "tokens_per_minute": 0,
        "requests_per_minute": 0,
        "max_retries": 10,
        "max_retry_wait": 10.0,
        "sleep_on_rate_limit_recommendation": true,
        "concurrent_requests": 25
    },
    "parallelization": {
        "stagger": 0.3,
        "num_threads": 50
    },
    "async_mode": "threaded",
    "root_dir": "/Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline",
    "reporting": {
        "type": "file",
        "base_dir": "/Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline/logs",
        "storage_account_blob_url": null
    },
    "storage": {
        "type": "file",
        "base_dir": "/Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline/output",
        "storage_account_blob_url": null
    },
    "update_index_storage": null,
    "cache": {
        "type": "file",
        "base_dir": "cache",
        "storage_account_blob_url": null
    },
    "input": {
        "type": "file",
        "file_type": "text",
        "base_dir": "input",
        "storage_account_blob_url": null,
        "encoding": "utf-8",
        "file_pattern": ".*\\.txt$",
        "file_filter": null,
        "source_column": null,
        "timestamp_column": null,
        "timestamp_format": null,
        "text_column": "text",
        "title_column": null,
        "document_attribute_columns": []
    },
    "embed_graph": {
        "enabled": false,
        "num_walks": 10,
        "walk_length": 40,
        "window_size": 2,
        "iterations": 3,
        "random_seed": 597832,
        "strategy": null
    },
    "embeddings": {
        "llm": {
            "api_key": "==== REDACTED ====",
            "type": "openai_embedding",
            "model": "text-embedding-3-large",
            "max_tokens": 4000,
            "temperature": 0,
            "top_p": 1,
            "n": 1,
            "request_timeout": 180.0,
            "api_base": null,
            "api_version": null,
            "proxy": null,
            "audience": null,
            "deployment_name": null,
            "model_supports_json": null,
            "tokens_per_minute": 0,
            "requests_per_minute": 0,
            "max_retries": 10,
            "max_retry_wait": 10.0,
            "sleep_on_rate_limit_recommendation": true,
            "concurrent_requests": 25
        },
        "parallelization": {
            "stagger": 0.3,
            "num_threads": 50
        },
        "async_mode": "threaded",
        "batch_size": 16,
        "batch_max_tokens": 8191,
        "target": "required",
        "skip": [],
        "vector_store": {
            "type": "lancedb",
            "db_uri": "output/lancedb",
            "container_name": "==== REDACTED ====",
            "overwrite": true
        },
        "strategy": null
    },
    "chunks": {
        "size": 1200,
        "overlap": 100,
        "group_by_columns": [
            "id"
        ],
        "strategy": null,
        "encoding_model": null
    },
    "snapshots": {
        "embeddings": false,
        "graphml": false,
        "raw_entities": false,
        "top_level_nodes": false,
        "transient": false
    },
    "entity_extraction": {
        "llm": {
            "api_key": "==== REDACTED ====",
            "type": "openai_chat",
            "model": "gpt-4o",
            "max_tokens": 4000,
            "temperature": 0.0,
            "top_p": 1.0,
            "n": 1,
            "request_timeout": 180.0,
            "api_base": null,
            "api_version": null,
            "proxy": null,
            "audience": null,
            "deployment_name": null,
            "model_supports_json": true,
            "tokens_per_minute": 0,
            "requests_per_minute": 0,
            "max_retries": 10,
            "max_retry_wait": 10.0,
            "sleep_on_rate_limit_recommendation": true,
            "concurrent_requests": 25
        },
        "parallelization": {
            "stagger": 0.3,
            "num_threads": 50
        },
        "async_mode": "threaded",
        "prompt": "prompts/entity_extraction.txt",
        "entity_types": [
            "Articles",
            "Sections/Chapters",
            "Rights and Freedoms",
            "Obligations and Duties",
            "Institutions and Bodies",
            "Government Entities",
            "Judicial Entities",
            "Other Entities",
            "Territorial References",
            "Competencies",
            "Procedural Terms",
            "Doctrines and Principles",
            "Dates and Deadlines",
            "Referenced Articles",
            "Referenced Laws or Documents",
            "Amendments",
            "Annotations and Clarifications",
            "Processes",
            "Roles in Processes",
            "Social and Political Values",
            "Cultural and Historical References"
        ],
        "max_gleanings": 1,
        "strategy": null,
        "encoding_model": null
    },
    "summarize_descriptions": {
        "llm": {
            "api_key": "==== REDACTED ====",
            "type": "openai_chat",
            "model": "gpt-4o",
            "max_tokens": 4000,
            "temperature": 0.0,
            "top_p": 1.0,
            "n": 1,
            "request_timeout": 180.0,
            "api_base": null,
            "api_version": null,
            "proxy": null,
            "audience": null,
            "deployment_name": null,
            "model_supports_json": true,
            "tokens_per_minute": 0,
            "requests_per_minute": 0,
            "max_retries": 10,
            "max_retry_wait": 10.0,
            "sleep_on_rate_limit_recommendation": true,
            "concurrent_requests": 25
        },
        "parallelization": {
            "stagger": 0.3,
            "num_threads": 50
        },
        "async_mode": "threaded",
        "prompt": "prompts/summarize_descriptions.txt",
        "max_length": 500,
        "strategy": null
    },
    "community_reports": {
        "llm": {
            "api_key": "==== REDACTED ====",
            "type": "openai_chat",
            "model": "gpt-4o",
            "max_tokens": 4000,
            "temperature": 0.0,
            "top_p": 1.0,
            "n": 1,
            "request_timeout": 180.0,
            "api_base": null,
            "api_version": null,
            "proxy": null,
            "audience": null,
            "deployment_name": null,
            "model_supports_json": true,
            "tokens_per_minute": 0,
            "requests_per_minute": 0,
            "max_retries": 10,
            "max_retry_wait": 10.0,
            "sleep_on_rate_limit_recommendation": true,
            "concurrent_requests": 25
        },
        "parallelization": {
            "stagger": 0.3,
            "num_threads": 50
        },
        "async_mode": "threaded",
        "prompt": "prompts/community_report.txt",
        "max_length": 2000,
        "max_input_length": 8000,
        "strategy": null
    },
    "claim_extraction": {
        "llm": {
            "api_key": "==== REDACTED ====",
            "type": "openai_chat",
            "model": "gpt-4o",
            "max_tokens": 4000,
            "temperature": 0.0,
            "top_p": 1.0,
            "n": 1,
            "request_timeout": 180.0,
            "api_base": null,
            "api_version": null,
            "proxy": null,
            "audience": null,
            "deployment_name": null,
            "model_supports_json": true,
            "tokens_per_minute": 0,
            "requests_per_minute": 0,
            "max_retries": 10,
            "max_retry_wait": 10.0,
            "sleep_on_rate_limit_recommendation": true,
            "concurrent_requests": 25
        },
        "parallelization": {
            "stagger": 0.3,
            "num_threads": 50
        },
        "async_mode": "threaded",
        "enabled": false,
        "prompt": "prompts/claim_extraction.txt",
        "description": "Any claims or facts that could be relevant to information discovery.",
        "max_gleanings": 1,
        "strategy": null,
        "encoding_model": null
    },
    "cluster_graph": {
        "max_cluster_size": 10,
        "strategy": null
    },
    "umap": {
        "enabled": false
    },
    "local_search": {
        "prompt": "prompts/local_search_system_prompt.txt",
        "text_unit_prop": 0.5,
        "community_prop": 0.1,
        "conversation_history_max_turns": 5,
        "top_k_entities": 10,
        "top_k_relationships": 10,
        "temperature": 0.0,
        "top_p": 1.0,
        "n": 1,
        "max_tokens": 12000,
        "llm_max_tokens": 2000
    },
    "global_search": {
        "map_prompt": "prompts/global_search_map_system_prompt.txt",
        "reduce_prompt": "prompts/global_search_reduce_system_prompt.txt",
        "knowledge_prompt": "prompts/global_search_knowledge_system_prompt.txt",
        "temperature": 0.0,
        "top_p": 1.0,
        "n": 1,
        "max_tokens": 12000,
        "data_max_tokens": 12000,
        "map_max_tokens": 1000,
        "reduce_max_tokens": 2000,
        "concurrency": 32,
        "dynamic_search_llm": "gpt-4o-mini",
        "dynamic_search_threshold": 1,
        "dynamic_search_keep_parent": false,
        "dynamic_search_num_repeats": 1,
        "dynamic_search_use_summary": false,
        "dynamic_search_concurrent_coroutines": 16,
        "dynamic_search_max_level": 2
    },
    "drift_search": {
        "prompt": "prompts/drift_search_system_prompt.txt",
        "temperature": 0.0,
        "top_p": 1.0,
        "n": 3,
        "max_tokens": 12000,
        "data_max_tokens": 12000,
        "concurrency": 32,
        "drift_k_followups": 20,
        "primer_folds": 5,
        "primer_llm_max_tokens": 12000,
        "n_depth": 3,
        "local_search_text_unit_prop": 0.9,
        "local_search_community_prop": 0.1,
        "local_search_top_k_mapped_entities": 10,
        "local_search_top_k_relationships": 10,
        "local_search_max_data_tokens": 12000,
        "local_search_temperature": 0.0,
        "local_search_top_p": 1.0,
        "local_search_n": 1,
        "local_search_llm_max_gen_tokens": 2000
    },
    "encoding_model": "cl100k_base",
    "skip_workflows": []
}
15:40:28,19 graphrag.index.create_pipeline_config INFO skipping workflows 
15:40:28,19 graphrag.index.run.run INFO Running pipeline
15:40:28,19 graphrag.index.storage.file_pipeline_storage INFO Creating file storage at /Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline/output
15:40:28,19 graphrag.index.input.load_input INFO loading input from root_dir=input
15:40:28,19 graphrag.index.input.load_input INFO using file storage for input
15:40:28,20 graphrag.index.storage.file_pipeline_storage INFO search /Users/adriandelasierra/Documents/python_projects/graphrag-pipeline/pipeline/input for files matching .*\.txt$
15:40:28,20 graphrag.index.input.text INFO found text files from input, found [('macron.txt', {})]
15:40:28,21 graphrag.index.input.text INFO Found 1 files, loading 1
15:40:28,22 graphrag.index.workflows.load INFO Workflow Run Order: ['create_base_text_units', 'create_final_documents', 'create_base_entity_graph', 'create_final_entities', 'create_final_nodes', 'create_final_communities', 'create_final_relationships', 'create_final_text_units', 'create_final_community_reports', 'generate_text_embeddings']
15:40:28,22 graphrag.index.run.run INFO Final # of rows loaded: 1
15:40:28,53 graphrag.index.run.workflow INFO dependencies for create_base_text_units: []
15:40:28,54 datashaper.workflow.workflow INFO executing verb create_base_text_units
15:40:28,979 graphrag.index.run.workflow INFO dependencies for create_final_documents: ['create_base_text_units']
15:40:28,979 graphrag.index.run.workflow WARNING Dependency table create_base_text_units not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
15:40:28,981 datashaper.workflow.workflow INFO executing verb create_final_documents
15:40:28,988 graphrag.index.emit.parquet_table_emitter INFO emitting parquet table create_final_documents.parquet
15:40:29,46 graphrag.index.run.workflow INFO dependencies for create_base_entity_graph: ['create_base_text_units']
15:40:29,46 graphrag.index.run.workflow WARNING Dependency table create_base_text_units not found in storage: it may be a runtime-only in-memory table. If you see further errors, this may be an actual problem.
15:40:29,48 datashaper.workflow.workflow INFO executing verb create_base_entity_graph
15:40:29,50 graphrag.llm.openai.create_openai_client INFO Creating OpenAI client base_url=None
15:40:29,86 graphrag.index.llm.load_llm INFO create TPM/RPM limiter for gpt-4o: TPM=0, RPM=0
15:40:29,86 graphrag.index.llm.load_llm INFO create concurrency limiter for gpt-4o: 25
15:41:08,97 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:41:08,109 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "Process" with 0 retries took 39.011768750002375. input_tokens=6088, output_tokens=1349
15:41:17,981 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:41:18,78 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "Process" with 0 retries took 48.986655875. input_tokens=6722, output_tokens=2318
15:41:20,585 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:41:20,587 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "extract-continuation-0" with 0 retries took 12.471234541997546. input_tokens=34, output_tokens=439
15:41:24,20 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:41:24,25 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "Process" with 0 retries took 54.930119959000876. input_tokens=6723, output_tokens=1968
15:42:03,702 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:42:03,713 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "extract-continuation-0" with 0 retries took 39.682967000000644. input_tokens=34, output_tokens=1714
15:42:12,989 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
15:42:13,247 graphrag.llm.base.rate_limiting_llm INFO perf - llm.chat "extract-continuation-0" with 0 retries took 55.16020845800085. input_tokens=34, output_tokens=3094
15:42:13,262 graphrag.index.operations.cluster_graph WARNING Graph has no nodes
15:42:13,266 datashaper.workflow.workflow ERROR Error executing verb "create_base_entity_graph" in create_base_entity_graph: Columns must be same length as key
Traceback (most recent call last):
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py", line 51, in create_base_entity_graph
    output = await create_base_entity_graph_flow(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/flows/create_base_entity_graph.py", line 77, in create_base_entity_graph
    clustered = cluster_graph(
                ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/operations/cluster_graph.py", line 90, in cluster_graph
    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)
    ~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
15:42:13,273 graphrag.callbacks.file_workflow_callbacks INFO Error executing verb "create_base_entity_graph" in create_base_entity_graph: Columns must be same length as key details=None
15:42:13,273 graphrag.index.run.run ERROR error running workflow create_base_entity_graph
Traceback (most recent call last):
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/run/run.py", line 274, in run_pipeline
    result = await _process_workflow(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/run/workflow.py", line 108, in _process_workflow
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
    result = await result
             ^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/workflows/v1/subflows/create_base_entity_graph.py", line 51, in create_base_entity_graph
    output = await create_base_entity_graph_flow(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/flows/create_base_entity_graph.py", line 77, in create_base_entity_graph
    clustered = cluster_graph(
                ^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/graphrag/index/operations/cluster_graph.py", line 90, in cluster_graph
    output[[level_to, to]] = pd.DataFrame(output[to].tolist(), index=output.index)
    ~~~~~~^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/frame.py", line 4341, in _setitem_array
    check_key_length(self.columns, key, value)
  File "/opt/miniconda3/envs/graphrag-pipeline/lib/python3.12/site-packages/pandas/core/indexers/utils.py", line 390, in check_key_length
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key
15:42:13,275 graphrag.callbacks.file_workflow_callbacks INFO Error running pipeline! details=None
15:42:13,283 graphrag.cli.index ERROR Errors occurred during the pipeline run, see logs for more details.

``` 

### Steps to reproduce

**Step 1.** Create the required pipeline structure:
```
mkdir -p ./pipeline/input
``` 
**Step 2.** Manually add a UTF-8 encoded text file (e.g., constitucion.txt) to the pipeline/input folder.

**Step 3.** Initialize the pipeline:
```
graphrag init --root ./pipeline
``` 
**Step 4.** Perform prompt autotuning:

```
python -m graphrag prompt-tune --root pipeline --config pipeline/settings.yaml --selection-method all --language Spanish --min-examples-required 5 --output pipeline/tuned-prompts
``` 
**Step 5.** Copy the generated tuned prompts to the pipeline's prompt folder.
**Step 6.** Run the indexing process:

```
graphrag index --root ./pipeline
``` 

### Expected Behavior

Indexing pipeline should run as expected and as usual, parquet files should be generated.

### GraphRAG Config Used

```yaml

encoding_model: cl100k_base # this needs to be matched to your model!

llm:
  api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
  type: openai_chat # or azure_openai_chat
  model: gpt-4o
  model_supports_json: true 

parallelization:
  stagger: 0.3
  # num_threads: 50

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store:
    type: lancedb
    db_uri: 'output/lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-large


### Input settings ###

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

cache:
  type: file # or blob
  base_dir: "cache"

reporting:
  type: file # or console, blob
  base_dir: "logs"

storage:
  type: file # or blob
  base_dir: "output"

## only turn this on if running `graphrag index` with custom settings
## we normally use `graphrag update` with the defaults
update_index_storage:
  # type: file # or blob
  # base_dir: "update_output"

### Workflow settings ###

skip_workflows: []

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [Articles, Sections/Chapters, Rights and Freedoms, Obligations and Duties, Institutions and Bodies, Government Entities, Judicial Entities, Other Entities, Territorial References, Competencies, Procedural Terms, Doctrines and Principles, Dates and Deadlines, Referenced Articles, Referenced Laws or Documents, Amendments, Annotations and Clarifications, Processes, Roles in Processes, Social and Political Values, Cultural and Historical References]
  max_gleanings: 1

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  enabled: false
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false
  embeddings: false
  transient: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  prompt: "prompts/drift_search_system_prompt.txt"

```

### Additional Information

- GraphRAG Version: tried with 0.5.0 and 0.4.1
- Operating System: macOS 15.1.1 (24B91)
- Python Version: tried 3.11, 3.12 and 3.13
