### ISSUE TITLE
[Bug]: AttributeError: 'list' object has no attribute 'on_error'

### ISSUE THREAD

**Issue by NathanAP** [microsoft/graphrag#1505]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

Sometimes when I try to `build_index`, I'm getting the following:

```python
index_result = await api.build_index(config=my_config) # this is me calling it
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/graphrag/api/index.py", line 73, in build_index
async for output in run_pipeline_with_config(
File "/usr/local/lib/python3.12/site-packages/graphrag/index/run/run.py", line 172, in run_pipeline_with_config
async for table in run_pipeline(
File "/usr/local/lib/python3.12/site-packages/graphrag/index/run/run.py", line 277, in run_pipeline
cast("WorkflowCallbacks", callbacks).on_error(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'on_error'
```

Not sure if there's anything I can do to fix it in my side...

### Steps to reproduce

This is happening very rarely, tbh. I didn't find a consist that makes it appear.

### Expected Behavior

Index should be done normally.

### GraphRAG Config Used

```yaml
# Paste your config here
async_mode: threaded
cache:
  base_dir: cache
  type: file
chunks:
  group_by_columns:
  - id
  overlap: 0
  size: 600
claim_extraction:
  description: Any claims or facts that could be relevant to information discovery.
  enabled: false
  max_gleanings: 1
  prompt: prompts/claim_extraction.txt
cluster_graph:
  max_cluster_size: 10
community_reports:
  max_input_length: 8000
  max_length: 2000
  prompt: prompts/community_report.txt
drift_search:
  prompt: prompts/drift_search_system_prompt.txt
embed_graph:
  enabled: false
embeddings:
  async_mode: threaded
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    model: text-embedding-3-small
    type: openai_embedding
  vector_store:
    container_name: default
    db_uri: output/lancedb
    overwrite: true
    type: lancedb
encoding_model: cl100k_base
entity_extraction:
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 1
  prompt: prompts/entity_extraction.txt
global_search:
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
  map_prompt: prompts/global_search_map_system_prompt.txt
  reduce_prompt: prompts/global_search_reduce_system_prompt.txt
input:
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$
  file_type: text
  type: file
llm:
  api_key: ${GRAPHRAG_API_KEY}
  model: gpt-4o-mini
  model_supports_json: true
  type: openai_chat
local_search:
  prompt: prompts/local_search_system_prompt.txt
parallelization:
  stagger: 0.3
reporting:
  base_dir: logs
  type: file
skip_workflows: []
snapshots:
  embeddings: false
  graphml: false
  transient: false
storage:
  base_dir: output
  type: file
summarize_descriptions:
  max_length: 500
  prompt: prompts/summarize_descriptions.txt
umap:
  enabled: false
update_index_storage: null

```

### Additional Information

- GraphRAG Version: 0.9.0
- Operating System: Linux
- Python Version: 3.12.7
- Related Issues: didn't find anything like it

**Comment by adhazel** [comment]
@NathanAP  I created my first graphrag project this morning and am running in the same problem. My steps are below and mostly from the getting started steps...

environment: Windows / Azure OpenAI 

1. Create a local folder
2. pip install poetry
3. poetry init
4. poetry shell
5. pip install graphrag
6. mkdir -p ./ragtest/input
7. curl https://www.gutenberg.org/cache/epub/24022/pg24022.txt -o ./ragtest/input/book.txt
8. Modify .env file with my AOAI key
9. Modify the settings.yaml file under "llm:" block. I modified the embedding block first and missed the first one.
10. graphrag index --root ./ragtest
11. I got the error ***
12. I modified the settings.yaml file under the FIRST llm block
13. I got the error ***

Other than running the index first and failing once due to not having the correct settings, it is pretty clean repro steps

**Comment by NathanAP** [comment]
In my case I'm using always the same file(s) to index it because we're using Playwright to make some end to end tests. This morning I got 3 times in a row this same error and then never happened again... 

TBH I have no idea if this is in our control to manage.

**Comment by alexfrocha** [comment]
me too

**Comment by YepJin** [comment]
same here, i just updated and found this bug

**Comment by natoverse** [comment]
Can someone with this error upload an indexing-engine.log so we can see the stack trace? I had the error myself yesterday with a largish dataset, and it was due to too many API requests (mine was on Azure OpenAI). It does not seem consistency, so may be temporary instability issues?

**Comment by xldistance** [comment]
@natoverse settings.yaml
```
llm:
  # exllamav2
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: Rombos-LLM-V2.5-Qwen-32b-4.5bpw-exl2
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 16000
  api_base: http://127.0.0.1:5001/v1
  requests_per_minute: 5_000 # set a leaky bucket throttle
  max_retries: 10
  max_retry_wait: 0
```
graphrag 1.0 does not call the api_base inside llm, and uses the default api_base of openai, resulting in model authentication errors,The error log is as follows:
11:34:31,347 httpx INFO HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 401 Unauthorized"
