### ISSUE TITLE
[Bug]: TypeError: create_blob_storage() got an unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by mctarsi** [microsoft/graphrag#1514]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

I configure the config.yml to include Azure blob container as storage. The configuration is:

```yaml
storage:
  type: blob
  connection_string: XXX
  container_name: output
  base_dir: output
```

When I launch the graphrag.index, there is this error:
TypeError: create_blob_storage() got an unexpected keyword argument 'type'

This is due to the fact that in the create_blob_storage() function contained in graphrag/storage/blob_pipeline_storage.py file, it is not considered 'type' parameter. 

The parameters should be passed in the function definition (line 293):
```python
def create_blob_storage(
    connection_string: str | None,
    storage_account_blob_url: str | None,
    container_name: str,
    base_dir: str | None,
) -> PipelineStorage:
```

### Steps to reproduce

1. Configure YAML file config.yml 
2. Launch graphrag index --root ./ragtest 

### Expected Behavior

I expected to load the artifacts, final outputs, in Azure blob storage. To do that it should be execute create_blob_storage function with every parameters. 

### GraphRAG Config Used

```yaml
storage:
  type: blob
  connection_string: XXX
  container_name: output
  base_dir: output

```

### Logs and screenshots

![Image](https://github.com/user-attachments/assets/c5e38d36-a744-4b64-b13d-8557841d627d)

### Additional Information

- GraphRAG Version: v1.0.0
- Operating System: Windows 10 Enterprise
- Python Version: 3.12.4
- Related Issues:
