### ISSUE TITLE
[Bug]: graphrag index creates 637 AsyncAzureOpenAI on gutenberg QuickStart

### ISSUE THREAD

**Issue by mmaitre314** [microsoft/graphrag#1517]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

GraphRAG v1.0.0 keeps on calling `fnllm.openai.create_openai_client()` during indexing instead of reusing the OpenAI client. Since fnllm creates a new `DefaultAzureCredential` for each `create_openai_client()` call ([code](https://github.com/engchina/fnllm/blob/8f569c9243a5735d8c4c93764165f3f7d1937092/fnllm/openai/factories/client.py#L16)), this restarts the authentication process and adds to indexing runtime.

### Steps to reproduce

Follow the GraphRAG quickstart (https://microsoft.github.io/graphrag/get_started/) until the step `graphrag index --root ./ragtest`, using Entra authentication instead of API key. Open indexing-engine.log and observe repeated log lines like this:
```
azure.identity._credentials.managed_identity INFO ManagedIdentityCredential will use IMDS
```

### Expected Behavior

The OpenAI client is reused and only one Entra access token is acquired for authentication.

### GraphRAG Config Used

```yaml
encoding_model: o200k_base

llm:
  type: azure_openai_chat
  model: gpt-4o-mini
  model_supports_json: true
  api_base: https://<snip>.openai.azure.com
  api_version: 2024-08-01-preview
  deployment_name: gpt-4o-mini

parallelization:
  stagger: 0.3
  # num_threads: 50

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store:
    type: lancedb
    db_uri: 'output\lancedb'
    container_name: default
    overwrite: true
  llm:
    type: azure_openai_embedding
    model: text-embedding-3-small
    api_base: https://<snip>.openai.azure.com
    api_version: "2023-05-15"
    deployment_name: text-embedding-3-small

### Input settings ###

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "../../inputs/gutenberg"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

cache:
  type: file # or blob
  base_dir: "cache"

reporting:
  type: file # or console, blob
  base_dir: "logs"

storage:
  type: file # or blob
  base_dir: "output"

## only turn this on if running `graphrag index` with custom settings
## we normally use `graphrag update` with the defaults
update_index_storage:
  # type: file # or blob
  # base_dir: "update_output"

### Workflow settings ###

skip_workflows: []

entity_extraction:
  prompt: "../../prompts/default/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  prompt: "../../prompts/default/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  enabled: false
  prompt: "../../prompts/default/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "../../prompts/default/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  embeddings: false
  transient: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  prompt: "../../prompts/default/local_search_system_prompt.txt"

global_search:
  map_prompt: "../../prompts/default/global_search_map_system_prompt.txt"
  reduce_prompt: "../../prompts/default/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "../../prompts/default/global_search_knowledge_system_prompt.txt"

drift_search:
  prompt: "../../prompts/default/drift_search_system_prompt.txt"
```

### Additional Information

- GraphRAG Version: 1.0.0
- Operating System: Windows 11
- Python Version: 3.12
- Related Issues:
