### ISSUE TITLE
[Issue]: How to remove redundancy from GraphRAG prompt?

### ISSUE THREAD

**Issue by SushmitaSingh96** [microsoft/graphrag#1531]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

The following is the request I received on the server side from GraphRAG. I am using vllm to run local models.  The prompt appears to be repeating the same information again and again. Is this how this is supposed to be? How can I correct this?
```bash
INFO 12-17 13:18:17 logger.py:37] Received request chatcmpl-dc36a3d0e9184d638f7b592e4b1b2405: prompt: '<s>[INST] i\nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain. You are skilled at identifying the relations and structure of the community of interest. You are adept at helping people with identifying the relations and structure of the community of interest.\n\ntask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\npersona description: \nYou are an expert in the tax domain\n\n\nThe goal is to study the connections and relations between the entity types and their features in order to understand all available information from the text.\nThe user\'s task is to \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n.\nAs part of the analysis, you want to identify the entity types present in the following text.\nThe entity types must be relevant to the user task.\nAvoid general entity types such as "other" or "unknown".\nThis is VERY IMPORTANT: Do not generate redundant or overlapping entity types. For example, if the text contains "company" and "organization" entity types, you should return only one of them.\nDon\'t worry about quantity, always choose quality over quantity. And make sure EVERYTHING in your answer is relevant to the context of entity extraction.\nReturn the entity types in JSON format with "entities" as the key and the entity types as an array of strings.\n=====================================================================\nEXAMPLE SECTION: The following section includes example output. These examples **must be excluded from your answer**.\n\nEXAMPLE 1\nTask: Determine the connections and organizational hierarchy within the specified community.\nText: Example_Org_A is a company in Sweden. Example_Org_A\'s director is Example_Individual_B.\nJSON RESPONSE:\n{"entity_types": [organization, person] }\nEND OF EXAMPLE 1\n\nEXAMPLE 2\nTask: Identify the key concepts, principles, and arguments shared among different philosophical schools of thought, and trace the historical or ideological influences they have on each other.\nText: Rationalism, epitomized by thinkers such as René Descartes, holds that reason is the primary source of knowledge. Key concepts within this school include the emphasis on the deductive method of reasoning.\nJSON RESPONSE:\n{"entity_types": [concept, person, school of thought] }\nEND OF EXAMPLE 2\n\nEXAMPLE 3\nTask: Identify the full range of basic forces, factors, and trends that would indirectly shape an issue.\nText: Industry leaders such as Panasonic are vying for supremacy in the battery production sector. They are investing heavily in research and development and are exploring new technologies to gain a competitive edge.\nJSON RESPONSE:\n{"entity_types": [organization, technology, sectors, investment strategies] }\nEND OF EXAMPLE 3\n======================================================================\n\n======================================================================\nREAL DATA: The following section is the real data. You should use only this real data to prepare your answer. Generate Entity Types only.\nTask: \nIdentify the relations and structure of the community of interest, specifically within the tax domain.\n\nText: ...\nJSON response:\n{"entity_types": [<entity_types>] }\n[/INST]', params: SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.0, top_p=1.0, top_k=-1, min_p=0.0, seed=None, stop=[], stop_token_ids=[], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=4000, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, guided_decoding=GuidedDecodingParams(json=None, regex=None, choice=None, grammar=None, json_object=True, backend=None, whitespace_pattern=None)), prompt_token_ids: None, lora_request: None, prompt_adapter_request: None.
```

### GraphRAG Config Used

```yaml
encoding_model: cl100k_base # this needs to be matched to your model!

llm:
  api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
  type: openai_chat # or azure_openai_chat
  model: /path/to/LlamaFinetuneBase_Mistral-Nemo-12B
  model_supports_json: true # recommended if this is available for your model.
  # audience: "https://cognitiveservices.azure.com/.default"
  # api_base: https://<instance>.openai.azure.com
  api_base: http://localhost:8000/v1
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>

parallelization:
  stagger: 0.3
  # num_threads: 50

async_mode: threaded # or asyncio

embeddings:
  async_mode: threaded # or asyncio
  vector_store: 
    type: lancedb
    db_uri: 'output/lancedb'
    container_name: default
    overwrite: true
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: /path/to/models/intfloat_e5-mistral-7b-instruct
    api_base: http://localhost:8001/v1
    # api_base: https://<instance>.openai.azure.com
    # api_version: 2024-02-15-preview
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>

### Input settings ###

input:
  type: file # or blob
  file_type: csv # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.csv$"

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

### Storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

cache:
  type: file # or blob
  base_dir: "cache"

reporting:
  type: file # or console, blob
  base_dir: "logs"

storage:
  type: file # or blob
  base_dir: "output"

## only turn this on if running `graphrag index` with custom settings
## we normally use `graphrag update` with the defaults
update_index_storage:
  # type: file # or blob
  # base_dir: "update_output"

### Workflow settings ###

skip_workflows: []

entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  enabled: false
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  embeddings: false
  transient: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  prompt: "prompts/drift_search_system_prompt.txt"


```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:
