### ISSUE TITLE
[Bug]: Code cleanup v1.0.0 blob_storage arguments

### ISSUE THREAD

**Issue by intelligencecompany** [microsoft/graphrag#1538]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The adjustment of the arguments is causing errors during indexing for the blob storage settings.

**For example:** #1482 line 39 (return create_blob_storage(**kwargs)). Where kwargs contains the property 'type', which is not expected by the function.

Ran into multiple locations, that this causes an error during indexing.

### Steps to reproduce

#1482 line 39 (return create_blob_storage(**kwargs)).

### Expected Behavior

Should be handled like:

```python
def create_file_storage(**kwargs: Any) -> PipelineStorage:
        """Create a file based storage."""
        **base_dir = kwargs["base_dir"]**
        log.info("Creating file storage at %s", base_dir)
        return FilePipelineStorage(root_dir=base_dir)
````

### GraphRAG Config Used

```yaml
# Paste your config here

storage:
  type: blob # or blob
  base_dir: "output"
  connection_string: "${GRAPHRAG_STORAGE_CONNECTION_STRING}"
  storage_account_blob_url: "${GRAPHRAG_STORAGE_ACCOUNT_BLOB_URL}"
  container_name: "${GRAPHRAG_STORAGE_CONTAINER_NAME}"

```

### Additional Information

- GraphRAG Version: 1.0.0
- Operating System: Win
- Python Version: 3.11.9
- Related Issues: #1514
