### ISSUE TITLE
[Bug]: DRIFT query method doese not work when using Azure AI Search as vector store

### ISSUE THREAD

**Issue by joskobasica** [microsoft/graphrag#1642]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

When using Azure AI search as a vector store, querying with drift method produces the following error:

` ValueError: Query and document embeddings are not compatible. Please ensure that the embeddings are of the same type and length.`

(The drift query method works when i use lance db as a local vector store)

When using Azure AI search as my vector store the  local and global query method work fine and provide a full response without any failures.  

This is my settings.yml:

```Yaml
encoding_model: cl100k_base

# Basic LLM settings for text generation
llm:
  type: azure_openai_chat
  api_key: ${GRAPHRAG_API_KEY}
  model: gpt-4o
  api_base: https://xxxxxxxxxx.openai.azure.com 
  api_version: "2024-08-01-preview"
  deployment_name: "gpt-4o-mini"
  max_tokens: 4000
  temperature: 0

# Embedding settings
embeddings:
  llm:
    type: azure_openai_embedding
    api_key: ${EMBEDDING_API_KEY}
    model: text-embedding-3-small
    api_base: https://jxxxxxxxxxx.cognitiveservices.azure.com
    api_version: "2024-02-15-preview"  
    deployment_name: "text-embedding-3-small"

  batch_size: 16  
  batch_max_tokens: 8191  
  target: "required"
  vector_store:
    type: azure_ai_search
    url: "https://xxxxxxxxxx.search.windows.net"
    api_key: "${AZURE_SEARCH_API_KEY}"
    api_version: "2023-11-01"
    vector_search_configuration_name: "default-vector-config"
    vector_search_profile_name: "vector-profile"
    vector_search_dimensions: 1024  
    indexes:
      default-entity-description:
        name: "default-entity-description"
        fields:
          - name: "id"
            type: "Edm.String"
            key: true
            searchable: true
          - name: "text"
            type: "Edm.String"
            searchable: true
          - name: "vector"
            type: "Collection(Edm.Single)"
            searchable: true
            filterable: false
            dimensions: 1024
            vectorSearchConfiguration: "default-vector-config"
          - name: "attributes"
            type: "Edm.String"
            searchable: false

# Input settings
input:
  type: file
  file_type: text
  base_dir: input
  file_encoding: utf-8
  file_pattern: .*\.txt$

# Storage settings
storage:
  type: file
  base_dir: output

# Cache settings
cache:
  type: file
  base_dir: cache

# Text chunking settings
chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]

# Enable required snapshots
snapshots:
  graphml: true
  embeddings: true

# Entity extraction settings
entity_extraction:
  prompt: "prompts/entity_extraction.txt"
  entity_types: ["organization", "person", "event", "geo"]
  max_gleanings: 1

# Community reports settings
community_reports:
  prompt: "prompts/community_report.txt"
  max_length: 2000

# Search configurations
drift_search:
  prompt: "prompts/drift_search_system_prompt.txt"
  max_tokens: 12000
  primer_folds: 2
  n_depth: 2
```

I have tried using these settings additionally in my `settings.yml`

```Yaml
    vector_search_configuration_name: "default-vector-config"
    vector_search_profile_name: "vector-profile"
    vector_search_dimensions: 1536 # also tried 1024  
```
And I have tried specifying the index settings directly:

```Yaml
    indexes:
      default-entity-description:
        name: "default-entity-description"
        fields:
          - name: "id"
            type: "Edm.String"
            key: true
            searchable: true
          - name: "text"
            type: "Edm.String"
            searchable: true
          - name: "vector"
            type: "Collection(Edm.Single)"
            searchable: true
            filterable: false
            dimensions: 1536 # and1024
            vectorSearchConfiguration: "default-vector-config"
          - name: "attributes"
            type: "Edm.String"
            searchable: false
```

All these changes resulted in the same ValueError mentions above.

Versions:
Python 3.10.16
graphrag 1.2.0 (problem was persistant in 1,1,0 also)
Ubuntu 22.04.5 LTS on WSL

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:
