### ISSUE TITLE
[Issue]: LLM configuration error detected [Azure OpenAI]

### ISSUE THREAD

**Issue by nishtha82** [microsoft/graphrag#1840]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Hello!! I am trying to setup as per get_started.md
On running 
`graphrag index --root ./ragtest`
using azure resource in the settings.yaml and getting `"HTTP/1.1 200 OK"` in log file
but indexing is not successfull and I get the error -

 31                                                                        |
|   32     try:                                                               |
|   33         asyncio.run(llm.achat("This is an LLM connectivity test. Say H |
| > 34         logger.success("LLM Config Params Validated")                  |
|   35     except Exception as e:  # noqa: BLE001                             |
|   36         logger.error(f"LLM configuration error detected. Exiting...\n{ |
|   37         sys.exit(1)      
.
.
.
.
+-----------------------------------------------------------------------------+
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f680' in
position 0: character maps to <undefined>

Not sure what is the problem?
Any help will be appreciated!
Python version - 3.11.9
system - windows
poetry version - 1.8.3

### Steps to reproduce

Following same steps as in get_started.md

### GraphRAG Config Used

```yaml

### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/
### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.
models:
  default_chat_model:
    type: azure_openai_chat
    api_base: @@my_api_azure@@
    api_version: "2024-06-01"
    auth_type: api_key # azure_managed_identity
    api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    model: gpt-4o
    deployment_name: gpt-4o
    # encoding_model: cl100k_base # automatically set by tiktoken if left undefined
    model_supports_json: true # recommended if this is available for your model.
    concurrent_requests: 2 # max number of simultaneous LLM requests allowed
    async_mode: threaded # or asyncio
    retry_strategy: native
    max_retries: -1 # set to -1 for dynamic retry logic (most optimal setting based on server response)
    tokens_per_minute: 0 # set to 0 to disable rate limiting
    requests_per_minute: 0 # set to 0 to disable rate limiting
  default_embedding_model:
    type: azure_openai_embedding #azure_openai_embedding # or 
    api_base: @@my_api_azure@@
    api_version: "2024-06-01"
    auth_type: api_key # azure_managed_identity
    api_key: ${GRAPHRAG_API_KEY}
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    model: text-embedding-3-small
    deployment_name: text-embedding-3-small
    # encoding_model: cl100k_base # automatically set by tiktoken if left undefined
    model_supports_json: true # recommended if this is available for your model.
    concurrent_requests: 25 # max number of simultaneous LLM requests allowed
    async_mode: threaded # or asyncio
    retry_strategy: native
    max_retries: -1 # set to -1 for dynamic retry logic (most optimal setting based on server response)
    tokens_per_minute: 0 # set to 0 to disable rate limiting
    requests_per_minute: 0 # set to 0 to disable rate limiting
vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output\lancedb
    container_name: default
    overwrite: True
embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store
### Input settings ###
input:
  type: file # or blob
  file_type: text # [csv, text, json]
  base_dir: "input"
chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]
### Output settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided
cache:
  type: file # [file, blob, cosmosdb]
  base_dir: "cache"
reporting:
  type: file # [file, blob, cosmosdb]
  base_dir: "logs"
output:
  type: file # [file, blob, cosmosdb]
  base_dir: "output"
### Workflow settings ###
extract_graph:
  model_id: default_chat_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1
summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500
extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english # [regex_english, syntactic_parser, cfg]
extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1
community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000
cluster_graph:
  max_cluster_size: 10
embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
umap:
  enabled: false # if true, will generate UMAP embeddings for nodes (embed_graph must also be enabled)
snapshots:
  graphml: false
  embeddings: false
### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"
global_search:
  chat_model_id: default_chat_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"
drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"
basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"

```

### Additional Information

- GraphRAG Version: 2.1.0
- Operating System: windows
- Python Version: 3.11.9
- Related Issues:
