### ISSUE TITLE
[Bug]: Auto Prompt Tuning - empty text in community_report_graph.txt

### ISSUE THREAD

**Issue by ashkan-software2** [microsoft/graphrag#1914]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [x] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [x] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

The `input` field in the community_report_graph.txt is empty after auto prompt tuning:

```
# Example Input
-----------
Text:   <---- here is empty!

Entities

id,entity,description
5,VERDANT OASIS PLAZA,Verdant Oasis Plaza is the location of the Unity March
6,HARMONY ASSEMBLY,Harmony Assembly is an organization that is holding a march at Verdant Oasis Plaza

Relationships
...

```

### Steps to reproduce

1- run auto prompt tuning for a PDF. For example this PDF: https://www.imf.org/-/media/Files/Publications/CR/2024/English/1USAEA2024001.ashx

### Expected Behavior

The `input` field should have a paragraph, then the entities, relationships, etc.  But the text is just empty :)

### GraphRAG Config Used

```yaml
models:
  default_chat_model:
    type: openai_chat
    auth_type: api_key
    api_key: ${GRAPHRAG_API_KEY}
    model: gpt-4-turbo-preview
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: -1
    tokens_per_minute: 0
    requests_per_minute: 0
  default_embedding_model:
    type: openai_embedding
    auth_type: api_key
    api_key: ${GRAPHRAG_API_KEY}
    model: text-embedding-3-small
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: -1
    tokens_per_minute: 0
    requests_per_minute: 0
vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output/lancedb
    container_name: default
    overwrite: true
embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store
input:
  type: file
  file_type: json
  base_dir: input
  text_column: page_content
  title_column: title
  metadata:
  - page
  - data_type
  - figures
chunks:
  size: 1200
  overlap: 100
  group_by_columns:
  - id
cache:
  type: file
  base_dir: cache
reporting:
  type: file
  base_dir: logs
output:
  type: file
  base_dir: output
extract_graph:
  model_id: default_chat_model
  prompt: prompts/extract_graph.txt
  entity_types:
  - organization
  - person
  - geo
  - event
  max_gleanings: 1
summarize_descriptions:
  model_id: default_chat_model
  prompt: prompts/summarize_descriptions.txt
  max_length: 500
extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english
extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: prompts/extract_claims.txt
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 1
community_reports:
  model_id: default_chat_model
  graph_prompt: prompts/community_report_graph.txt
  text_prompt: prompts/community_report_text.txt
  max_length: 2000
  max_input_length: 8000
cluster_graph:
  max_cluster_size: 10
embed_graph:
  enabled: false
umap:
  enabled: false
snapshots:
  graphml: false
  embeddings: false
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/local_search_system_prompt.txt
global_search:
  chat_model_id: default_chat_model
  map_prompt: prompts/global_search_map_system_prompt.txt
  reduce_prompt: prompts/global_search_reduce_system_prompt.txt
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/drift_search_system_prompt.txt
  reduce_prompt: prompts/drift_search_reduce_prompt.txt
basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/basic_search_system_prompt.txt


```

### Logs and screenshots

Content of community_report_graph.txt:

```

You are an expert in Economic Policy Analysis with a focus on community structures. You are skilled at applying quantitative and qualitative methods to assess economic policies and their impacts on different community segments. You are adept at helping people understand the intricate relations and structures within communities, particularly how economic policies influence social and economic outcomes. Your expertise includes network analysis, econometrics, and policy evaluation, making you well-equipped to dissect and explain the complex dynamics of economic policy effects on community structures.

# Goal
Write a comprehensive assessment report of a community taking on the role of a **Economic Policy Analyst for Community Impact Assessment**

**Role Definition:**

An Economic Policy Analyst for Community Impact Assessment is tasked with evaluating the effects of economic policies on various community segments, utilizing a blend of quantitative and qualitative analysis methods. This role involves:

- Analyzing economic indicators such as Liquid assets to total assets ratios, Household debt to GDP ratios, and the impacts of supply chain diversification efforts on community economic structures.
- Assessing the implications of fiscal adjustments, trade policies, and monetary policy shifts on community welfare, employment, and income distribution.
- Evaluating risks and policy responses as outlined in economic reports, focusing on inflation expectations, cyber threats, financial conditions tightening, and labor force participation recovery.
- Interpreting data from tables and graphs related to the United States' medium-term financial risks, including debt fanchart and GFN financeability indexes, to understand their potential community impacts.
- Collaborating with multiple agencies to develop policy responses aimed at enhancing community resilience against economic disruptions highlighted by global events such as the COVID-19 pandemic and geopolitical tensions.
- Providing comprehensive analysis on the effectiveness of policy measures in addressing economic vulnerabilities within communities, with a focus on fiscal health, banking system stability, and labor market dynamics.
- Communicating findings to decision-makers, community leaders, and the public to inform on significant developments and their potential impacts on community structures.

The report generated by the Economic Policy Analyst for Community Impact Assessment will serve as a critical resource for policymakers, community organizations, and economic development practitioners, offering insights into the nuanced effects of economic policies on different community segments and recommending strategies for fostering economic resilience and inclusive growth.. The content of this report includes an overview of the community's key entities and relationships.

# Report Structure
The report should include the following sections:
- TITLE: community's name that represents its key entities - title should be short but specific. When possible, include representative named entities in the title.
- SUMMARY: An executive summary of the community's overall structure, how its entities are related to each other, and significant information associated with its entities.
- REPORT RATING: A float score between 0-10 that represents the relevance of the text to economic policy analysis, with a focus on community structures, economic impacts on different community segments, and the influence of economic policies on social and economic outcomes. The score reflects the degree to which the data provides insights into the dynamics of economic policy effects on community structures, including network analysis, econometrics, and policy evaluation, with 1 being trivial or irrelevant and 10 being highly significant, profound, and impactful to the understanding of economic policy analysis in the context of community structures and outcomes.
- RATING EXPLANATION: Give a single sentence explanation of the rating.
- DETAILED FINDINGS: A list of 5-10 key insights about the community. Each insight should have a short summary followed by multiple paragraphs of explanatory text grounded according to the grounding rules below. Be comprehensive.

Return output as a well-formed JSON-formatted string with the following format. Don't use any unnecessary escape sequences. The output should be a single JSON object that can be parsed by json.loads.
    {
        "title": <report_title>,
        "summary": <executive_summary>,
        "rating": <impact_severity_rating>,
        "rating_explanation": <rating_explanation>,
        "findings": [
            {
                "summary":<insight_1_summary>,
                "explanation": <insight_1_explanation>
            },
            {
                "summary":<insight_2_summary>,
                "explanation": <insight_2_explanation>
            }
        ]
    }

# Grounding Rules
Points supported by data should list their data references as follows:

"This is an example sentence supported by multiple data references [Data: <dataset name> (record ids); <dataset name> (record ids)]."

Do not list more than 5 record ids in a single reference. Instead, list the top 5 most relevant record ids and add "+more" to indicate that there are more.

For example:
"Person X is the owner of Company Y and subject to many allegations of wrongdoing [Data: Reports (1), Entities (5, 7); Relationships (23); Claims (7, 2, 34, 64, 46, +more)]."

where 1, 5, 7, 23, 2, 34, 46, and 64 represent the id (not the index) of the relevant data record.

Do not include information where the supporting evidence for it is not provided.

# Example Input
-----------
Text:

Entities

id,entity,description
5,VERDANT OASIS PLAZA,Verdant Oasis Plaza is the location of the Unity March
6,HARMONY ASSEMBLY,Harmony Assembly is an organization that is holding a march at Verdant Oasis Plaza

Relationships

id,source,target,description
37,VERDANT OASIS PLAZA,UNITY MARCH,Verdant Oasis Plaza is the location of the Unity March
38,VERDANT OASIS PLAZA,HARMONY ASSEMBLY,Harmony Assembly is holding a march at Verdant Oasis Plaza
39,VERDANT OASIS PLAZA,UNITY MARCH,The Unity March is taking place at Verdant Oasis Plaza
40,VERDANT OASIS PLAZA,TRIBUNE SPOTLIGHT,Tribune Spotlight is reporting on the Unity march taking place at Verdant Oasis Plaza
41,VERDANT OASIS PLAZA,BAILEY ASADI,Bailey Asadi is speaking at Verdant Oasis Plaza about the march
43,HARMONY ASSEMBLY,UNITY MARCH,Harmony Assembly is organizing the Unity March

Output:
{
    "title": "Verdant Oasis Plaza and Unity March",
    "summary": "The community revolves around the Verdant Oasis Plaza, which is the location of the Unity March. The plaza has relationships with the Harmony Assembly, Unity March, and Tribune Spotlight, all of which are associated with the march event.",
    "rating": 5.0,
    "rating_explanation": "The impact severity rating is moderate due to the potential for unrest or conflict during the Unity March.",
    "findings": [
        {
            "summary": "Verdant Oasis Plaza as the central location",
            "explanation": "Verdant Oasis Plaza is the central entity in this community, serving as the location for the Unity March. This plaza is the common link between all other entities, suggesting its significance in the community. The plaza's association with the march could potentially lead to issues such as public disorder or conflict, depending on the nature of the march and the reactions it provokes. [Data: Entities (5), Relationships (37, 38, 39, 40, 41,+more)]"
        },
        {
            "summary": "Harmony Assembly's role in the community",
            "explanation": "Harmony Assembly is another key entity in this community, being the organizer of the march at Verdant Oasis Plaza. The nature of Harmony Assembly and its march could be a potential source of threat, depending on their objectives and the reactions they provoke. The relationship between Harmony Assembly and the plaza is crucial in understanding the dynamics of this community. [Data: Entities(6), Relationships (38, 43)]"
        },
        {
            "summary": "Unity March as a significant event",
            "explanation": "The Unity March is a significant event taking place at Verdant Oasis Plaza. This event is a key factor in the community's dynamics and could be a potential source of threat, depending on the nature of the march and the reactions it provokes. The relationship between the march and the plaza is crucial in understanding the dynamics of this community. [Data: Relationships (39)]"
        },
        {
            "summary": "Role of Tribune Spotlight",
            "explanation": "Tribune Spotlight is reporting on the Unity March taking place in Verdant Oasis Plaza. This suggests that the event has attracted media attention, which could amplify its impact on the community. The role of Tribune Spotlight could be significant in shaping public perception of the event and the entities involved. [Data: Relationships (40)]"
        }
    ]
}

# Real Data

Use the following text for your answer. Do not make anything up in your answer.

Text:
{input_text}
Output:
```

### Additional Information

- GraphRAG Version: 2.1.0
- Operating System: Linux
- Python Version: 3.11.2
- Related Issues:
