### ISSUE TITLE
[Bug]: <title>index  build_index method data is IndexingMethod.Fast triggered  'edge_df[["source", "target"]] = edge_df.loc[:, "edges"].to_list()'   edge_df is null

### ISSUE THREAD

**Issue by libalazzy** [microsoft/graphrag#1926]
### Do you need to file an issue?

- [x] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

  return self.__pydantic_serializer__.to_python(
error running workflow extract_graph_nlp
Traceback (most recent call last):
  File "C:\Users\dongliang\PycharmProjects\graphrag-2.2.1\graphrag\index\run\run_pipeline.py", line 129, in _run_pipeline
    result = await workflow_function(config, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongliang\PycharmProjects\graphrag-2.2.1\graphrag\index\workflows\extract_graph_nlp.py", line 27, in run_workflow
    entities, relationships = await extract_graph_nlp(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongliang\PycharmProjects\graphrag-2.2.1\graphrag\index\workflows\extract_graph_nlp.py", line 52, in extract_graph_nlp
    extracted_nodes, extracted_edges = await build_noun_graph(
                                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongliang\PycharmProjects\graphrag-2.2.1\graphrag\index\operations\build_noun_graph\build_noun_graph.py", line 33, in build_noun_graph
    edges_df = _extract_edges(nodes_df, normalize_edge_weights=normalize_edge_weights)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongliang\PycharmProjects\graphrag-2.2.1\graphrag\index\operations\build_noun_graph\build_noun_graph.py", line 110, in _extract_edges
    edge_df[["source", "target"]] = edge_df.loc[:, "edges"].to_list()
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dongliang\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4299, in __setitem__
    self._setitem_array(key, value)
  File "C:\Users\dongliang\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4358, in _setitem_array
    self._iset_not_inplace(key, value)
  File "C:\Users\dongliang\AppData\Local\Programs\Python\Python312\Lib\site-packages\pandas\core\frame.py", line 4377, in _iset_not_inplace
    raise ValueError("Columns must be same length as key")
ValueError: Columns must be same length as key

### Steps to reproduce

_No response_

### Expected Behavior

_No response_

### GraphRAG Config Used

```yaml
# settings.yaml
# Configuration file for GraphRAG
# For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
models:
  default_chat_model:
    type: openai_chat
    api_base: https://genaiapi.cloudsway.net/
    auth_type: api_key
    api_key: 421521521512512521
    model: 4omini
    encoding_model: cl100k_base
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: -1
    tokens_per_minute: 0
    requests_per_minute: 0
    temperature: 0.0
    top_p: 1.0
    n: 1
    frequency_penalty: 0.0
    presence_penalty: 0.0
    request_timeout: 180.0
    audience: https://cognitiveservices.azure.com/.default
  default_embedding_model:
    type: openai_embedding
    api_base: https://genaiapi.cloudsway.net/
    auth_type: api_key
    api_key: 521521521515215125151521
    model: large
    encoding_model: cl100k_base
    model_supports_json: true
    concurrent_requests: 25
    async_mode: threaded
    retry_strategy: native
    max_retries: -1
    tokens_per_minute: 0
    requests_per_minute: 0
    temperature: 0.0
    top_p: 1.0
    n: 1
    frequency_penalty: 0.0
    presence_penalty: 0.0
    request_timeout: 180.0
    audience: https://cognitiveservices.azure.com/.default

### Input settings ###
input:
  type: file
  file_type: text
  base_dir: input
  encoding: utf-8
  file_pattern: ""
  text_column: text

### Chunking settings ###
chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id]
  strategy: tokens
  encoding_model: cl100k_base
  prepend_metadata: false
  chunk_size_includes_metadata: false

### Output/storage settings ###
output:
  type: file
  base_dir: output

cache:
  type: file
  base_dir: cache

reporting:
  type: file
  base_dir: logs

vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output/lancedb
    container_name: default
    overwrite: true

### Workflow settings ###
embed_text:
  model: text-embedding-3-small
  batch_size: 16
  batch_max_tokens: 8191
  target: required
  model_id: default_embedding_model
  names: []
  vector_store_id: default_vector_store

extract_graph:
  model_id: default_chat_model
  prompt: prompts/extract_graph.txt
  entity_types: [organization, person, geo, event]
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: prompts/summarize_descriptions.txt
  max_length: 500
  max_input_tokens: 4000

extract_graph_nlp:
  normalize_edge_weights: true
  concurrent_requests: 25

text_analyzer:
  extractor_type: regex_english
  model_name: en_core_web_md
  max_word_length: 15
  word_delimiter: " "
  include_named_entities: true

cluster_graph:
  max_cluster_size: 10
  use_lcc: false
  seed: 42

extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: prompts/extract_claims.txt
  description: Any claims or facts that could be relevant to information discovery.
  max_gleanings: 1

community_reports:
  model_id: default_chat_model
  graph_prompt: prompts/community_report_graph.txt
  text_prompt: prompts/community_report_text.txt
  max_length: 2000
  max_input_length: 8000

embed_graph:
  enabled: false
  dimensions: 512
  num_walks: 10
  walk_length: 40
  window_size: 2
  iterations: 3
  random_seed: 42
  use_lcc: false

umap:
  enabled: false

snapshots:
  embeddings: false
  graphml: false
  raw_graph: false

prune_graph:
  min_node_freq: 2
  min_node_degree: 1
  min_edge_weight_pct: 40.0
  remove_ego_nodes: true
  lcc_only: false

### Query settings ###
local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/local_search_system_prompt.txt
  text_unit_prop: 0.5
  community_prop: 0.15
  conversation_history_max_turns: 5
  top_k_entities: 10
  top_k_relationships: 10
  max_context_tokens: 12000

global_search:
  chat_model_id: default_chat_model
  map_prompt: prompts/global_search_map_system_prompt.txt
  reduce_prompt: prompts/global_search_reduce_system_prompt.txt
  knowledge_prompt: prompts/global_search_knowledge_system_prompt.txt
  max_context_tokens: 12000
  data_max_tokens: 12000
  map_max_length: 1000
  reduce_max_length: 2000
  dynamic_search_threshold: 1
  dynamic_search_keep_parent: false
  dynamic_search_num_repeats: 1
  dynamic_search_use_summary: false
  dynamic_search_max_level: 2

drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/drift_search_system_prompt.txt
  reduce_prompt: prompts/drift_search_reduce_prompt.txt
  data_max_tokens: 12000
  reduce_temperature: 0.0
  concurrency: 25
  drift_k_followups: 3
  primer_folds: 5
  primer_llm_max_tokens: 4000
  n_depth: 2
  local_search_text_unit_prop: 0.5
  local_search_community_prop: 0.15
  local_search_top_k_mapped_entities: 10
  local_search_top_k_relationships: 10
  local_search_max_data_tokens: 12000
  local_search_temperature: 0.0
  local_search_top_p: 1.0
  local_search_n: 1

basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: prompts/basic_search_system_prompt.txt
  k: 10
  max_context_tokens: 12000

### Update index output settings ###
update_index_output:
  type: file
  base_dir: update_output

```


### Logs and screenshots

await index.build_index(config=graph_rag_config,method=IndexingMethod.Fast) method transmitting  Fast  problem has arisen ,There is no problem with standard

### Additional Information

- GraphRAG Version:2.2.1
- Operating System:
- Python Version:3.12
- Related Issues:
