### ISSUE TITLE
[Issue]: <title> Low Retrieval Performance in local_search for Factual Question-Answering Tasks

### ISSUE THREAD

**Issue by Furi5** [microsoft/graphrag#1980]
### Do you need to file an issue?

- [ ] I have searched the existing issues and this bug is not already filed.
- [ ] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [ ] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the issue

Hi GraphRAG Team,

First of all, thank you for creating such an ambitious and interesting project. I am currently evaluating GraphRAG's capabilities on a real-world task and have some performance results I'd like to share and discuss.

### Summary

I have built a document-level retrieval benchmark based on a corpus of over 1,000 scientific papers. The goal is to assess if `local_search` can retrieve the correct source document for a given factual question.

My evaluation shows a very low document-level Hit Rate, starting at 3.44% for @k=1 and reaching only 21.63% at @k=10. This suggests that for tasks requiring precise document provenance, the default `local_search` configuration may not be optimal.

### My Methodology

1.  **Corpus:** A collection of 1,000+ scientific papers in a specific domain `[e.g., pharmacology]`.
2.  **Benchmark Construction:** I created a set of question-document pairs. Each question is designed to have its answer contained within one specific "target document" in the corpus.
3.  **GraphRAG Indexing:** I indexed the entire corpus using the `graphrag --init` command with the `--init-method fast` setting.
4.  **Retrieval Step:** For each question in my benchmark, I run the `local_search` function.
5.  **Evaluation:** I inspect the `result.context_data["sources"]` field from the `local_search` output. A "hit" is counted if the ID of the "target document" is present in this list of sources. The Hit Rate @k is the percentage of questions for which the target document is found within the top *k* sources.

### Results

Here is the Hit Rate table from my benchmark:

| Hit Rate @1 | Hit Rate @2 | Hit Rate @3 | Hit Rate @4 | Hit Rate @5 | Hit Rate @6 | Hit Rate @7 | Hit Rate @8 | Hit Rate @9 | Hit Rate @10 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 3.44% | 8.33% | 11.20% | 13.11% | 15.79% | 17.03% | 19.14% | 20.38% | 21.34% | 21.63% |

*(Note: The percentages in the table are slightly adjusted for clarity if needed, but the trend is the key information)*

### Analysis & Hypothesis

These results were surprisingly low. My hypothesis is that there's a mismatch between my document-centric evaluation and the entity-centric design of `local_search`:

*   **Entity-Centric Synthesis:** `local_search` appears to prioritize creating a synthetic context from various graph elements (community reports, relationships, text chunks). In this process, it might extract the correct *information* from my target document but then prioritize a high-level community summary in the final context. This would cause the original document ID to be dropped from the final `sources` list, resulting in a "miss" in my evaluation, even if the information was found.
*   **Impact of `fast` mode:** The low quality of the graph generated by the `fast` method is likely a major contributing factor, as the search quality is dependent on the underlying graph's accuracy.
*   **Ranking Strategy:** The default ranking algorithm might not be tuned for tasks where retrieving the original, specific text chunk is more important than a generalized summary.

### Questions for the Team

1.  Is my understanding of `local_search`'s entity-centric behavior correct? Is it designed more for fact synthesis than for direct document retrieval?
2.  How much of this low performance would you attribute to the `--init-method fast`? Would you expect a dramatic improvement with the standard method?
3.  Are there configuration parameters within `local_search` or its `context_builder` that would allow me to **increase the priority of raw text chunks** over community reports, to make it perform better on this kind of document-level retrieval task?
4.  Is my evaluation methodology flawed for assessing GraphRAG? Do you have a recommendation for a better way to measure if the "correct information" was retrieved, beyond just checking the document ID in `sources`?

Thank you for your time and for this fantastic open-source tool. I'm hoping this feedback is useful and can lead to a discussion on how to best use (and perhaps improve) GraphRAG for high-precision retrieval tasks.

Happy to provide more details if needed.

### GraphRAG Config Used

```yaml
### This config file contains required core defaults that must be set, along with a handful of common optional settings.
### For a full list of available settings, see https://microsoft.github.io/graphrag/config/yaml/

### LLM settings ###
## There are a number of settings to tune the threading and token limits for LLM calls - check the docs.

models:
  default_chat_model:
    type: openai_chat # or azure_openai_chat
    api_base: http://0.0.0.0:8102/v1
    # api_version: 2024-05-01-preview
    auth_type: api_key # or azure_managed_identity
    api_key: ${GRAPHRAG_API_KEY} # set this in the generated .env file
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    model: /home/mindrank/fuli/DeepSeek-R1-32b
    request_timeout: 600 # seconds
    # deployment_name: <azure_model_deployment_name>
    encoding_model: cl100k_base # automatically set by tiktoken if left undefined
    model_supports_json: true # recommended if this is available for your model.
    concurrent_requests: 50 # max number of simultaneous LLM requests allowed
    async_mode: asyncio # or asyncio
    retry_strategy: native
    max_retries: 10
    max_tokens: 20000 # max number of tokens in a single request
    tokens_per_minute: 10000              # set to null to disable rate limiting
    requests_per_minute: 50            # set to null to disable rate limiting
    top_p: 0.99 # top_p is the nucleus sampling parameter, set to 0.0 to disable

  default_embedding_model:
    type: openai_embedding # or azure_openai_embedding
    api_base: http://localhost:11434/v1 
    # api_version: 2024-05-01-preview
    auth_type: api_key # or azure_managed_identity
    api_key: ${GRAPHRAG_API_KEY}
    # audience: "https://cognitiveservices.azure.com/.default"
    # organization: <organization_id>
    model: nomic-embed-text
    # deployment_name: <azure_model_deployment_name>
    encoding_model: cl100k_base # automatically set by tiktoken if left undefined
    model_supports_json: true # recommended if this is available for your model.
    concurrent_requests: 25 # max number of simultaneous LLM requests allowed
    async_mode: threaded # or asyncio
    retry_strategy: native
    max_retries: 10
    tokens_per_minute: 100000              # set to null to disable rate limiting
    requests_per_minute: 25            # set to null to disable rate limiting
    
### Input settings ###

input:
  type: file # or blob
  file_type: csv # [csv, text, json]
  title_column: pmid
  text_column: article
  metadata: [pmid]

chunks:
  size: 1200
  overlap: 100
  group_by_columns: [pmid]

### Output/storage settings ###
## If blob storage is specified in the following four sections,
## connection_string and container_name must be provided

output:
  type: file # [file, blob, cosmosdb]
  base_dir: "output"
    
cache:
  type: file # [file, blob, cosmosdb]
  base_dir: "cache"

reporting:
  type: file # [file, blob, cosmosdb]
  base_dir: "logs"

vector_store:
  default_vector_store:
    type: lancedb
    db_uri: output/lancedb
    container_name: default
    overwrite: True

### Workflow settings ###

embed_text:
  model_id: default_embedding_model
  vector_store_id: default_vector_store

extract_graph:
  model_id: default_chat_model
  prompt: "prompts/extract_graph.txt"
  entity_types: [disease,gene,pathway,protein,drug,chemical,cellular_component,biological_process,molecular_function]
  max_gleanings: 1

summarize_descriptions:
  model_id: default_chat_model
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

extract_graph_nlp:
  text_analyzer:
    extractor_type: regex_english # [regex_english, syntactic_parser, cfg]

cluster_graph:
  max_cluster_size: 10

extract_claims:
  enabled: false
  model_id: default_chat_model
  prompt: "prompts/extract_claims.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  model_id: default_chat_model
  graph_prompt: "prompts/community_report_graph.txt"
  text_prompt: "prompts/community_report_text.txt"
  max_length: 2000
  max_input_length: 8000

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes (embed_graph must also be enabled)

snapshots:
  graphml: false
  embeddings: false

### Query settings ###
## The prompt locations are required here, but each search method has a number of optional knobs that can be tuned.
## See the config docs: https://microsoft.github.io/graphrag/config/yaml/#query

local_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/local_search_system_prompt.txt"

global_search:
  chat_model_id: default_chat_model
  map_prompt: "prompts/global_search_map_system_prompt.txt"
  reduce_prompt: "prompts/global_search_reduce_system_prompt.txt"
  knowledge_prompt: "prompts/global_search_knowledge_system_prompt.txt"

drift_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/drift_search_system_prompt.txt"
  reduce_prompt: "prompts/drift_search_reduce_prompt.txt"

basic_search:
  chat_model_id: default_chat_model
  embedding_model_id: default_embedding_model
  prompt: "prompts/basic_search_system_prompt.txt"
```

### Additional Information

- GraphRAG Version: 2.3.0
- Operating System: linux
- Python Version: 3.11.11
