### ISSUE TITLE
ValueError:  `temperature` (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set `do_sample=False`.

### ISSUE THREAD

**Issue by CAICCU** [microsoft/graphrag#416]
This is my settings.yaml
`
settings.yaml
`
```
llm:
  api_key: EMPT
  api_base: http://0.0.0.0:9997/v1
  type: openai_chat # or azure_openai_chat
  model: chatglm3-6b # gpt-4-turbo-preview
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 4096
  # request_timeout: 180.0
  # api_base: https://<instance>.openai.azure.com
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
```

I use xinference api to run `python -m graphrag.index --root ./ragtest`,   
but in  `create_base_extracted_entities` step have bug in xinference:   
```ValueError:  `temperature` (=0.0) has to be a strictly positive float, otherwise your next token scores will be invalid. If you're looking for greedy decoding strategies, set `do_sample=False`.```  
How to solve it?
