### ISSUE TITLE
how to configure this with azure-openai?

### ISSUE THREAD

**Issue by VijayRameshkumar** [microsoft/graphrag#434]
Hi @jgbradley1 ,

Can you help me to configure by giving sample file..
what is organization parameter. is it api key for the organization?

encoding_model: cl100k_base
skip_workflows: []
llm:
  ----# api_key: ${GRAPHRAG_API_KEY}
  type: azure_openai_chat
  model: gpt-35-turbo-16k
  model_supports_json: false # recommended if this is available for your model.
  ----# max_tokens: 4000
  ---- # request_timeout: 180.0
  api_base: https://xxxxx.openai.azure.com/
  api_version: 2024-02-15-preview
  organization: 893xxxxxc675e2
  deployment_name: gpt-35-turbo-16k

-------------Received ERROR ---------------
File \"C:\\Users\\vijay.r\\anaconda\\envs\\ragagent\\lib\\site-packages\\openai\\_base_client.py\", line 1514, in request\n    return await self._request(\n  File \"C:\\Users\\vijay.r\\anaconda\\envs\\ragagent\\lib\\site-packages\\openai\\_base_client.py\", line 1610, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.

**Comment by AlonsoGuevara** [comment]
Hi @VijayRameshkumar 
For Azure-openai you don't need the organization actually :)

```yml
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: azure_openai_chat
  model: <model_name>
  model_supports_json: true # recommended if this is available for your model.
  api_base: https://<instance>.openai.azure.com
  api_version: 2024-02-15-preview
  deployment_name: <azure_model_deployment_name>
```
This is the minimal config or azure open ai chat.
Given your error I would double check the deployment name and endpoint base. I see you're using managed identities, so perhaps also double check that your assumed identity does indeed have access to that resource.

Please check this and reopen the issue if needed :)
