### ISSUE TITLE
create_final_covariates.parquet not generated[Bug]: <title>

### ISSUE THREAD

**Issue by win4r** [microsoft/graphrag#498]
### Describe the bug

create_final_covariates.parquet not generated

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by AlonsoGuevara** [comment]
Hi!
Please provide more information about the issue. Can you please add the config used?

**Comment by zanderjiang** [comment]
if you're using the default indexing pipeline it does not generate a create_final_covariates.parquet anymore. Set the covariates to [] or don't include it when defining a LocalSearchMixedContext class.

**Comment by win4r** [comment]
> if you're using the default indexing pipeline it does not generate a create_final_covariates.parquet anymore. Set the covariates to [] or don't include it when defining a LocalSearchMixedContext class.

What happens if I don't include covariates? How do I generate covariates?"

**Comment by zanderjiang** [comment]
> > if you're using the default indexing pipeline it does not generate a create_final_covariates.parquet anymore. Set the covariates to [] or don't include it when defining a LocalSearchMixedContext class.
> 
> What happens if I don't include covariates? How do I generate covariates?"

Covariates are claims associated with the extracted entities. I'm not entirely sure why they decided to disable the covariate file. I'm guessing it's because of reducing LLM calls? GraphRAG is very expensive to run even on small indexing tasks. 

Anyways, if you want to generate covariates, you can set GRAPHRAG_CLAIM_EXTRACTION_ENABLED to True in the .env file in your data project root. It should then generate the create_final_covariates.parquet file.

**Comment by AlonsoGuevara** [comment]
Thanks for your help @zanderjiang 
Absolutely correct.

Also, @win4r you can turn it on here:
```yaml
claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

```

Just uncomment the enabled line in your settings.yaml file.
I'll resolve the issue, but please reopen if this doesn't work
