### ISSUE TITLE
[file missing in output]: create_final_covariates

### ISSUE THREAD

**Issue by Rohith-Scalers** [microsoft/graphrag#508]
### Describe the bug

I have followed the indexing from docs , both local search and global search are running fine with commands . but when i am running them with py scripts from the example notebooks it is saying create_final_covariates is missing  . please let me know if there is any fixes . if possible please provide any references on output file formats.

### Steps to reproduce

by running .../artifacts file with localsearch example notebook from the repo

### Expected Behavior

create_final_covariates file is missing after indexing in artifacts folder

### GraphRAG Config Used

default

### Additional Information

- GraphRAG Version:
- Operating System:Ubantu 22
- Python Version:3.10
- Related Issues:

**Comment by Rohith-Scalers** [comment]
sloved by setting GRAPHRAG_CLAIM_EXTRACTION_ENABLED to True in .env

**Comment by AlonsoGuevara** [comment]
You can also turn it on in settings.yaml
```
claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1
```

Thanks for updating
