### ISSUE TITLE
[Issue]: <Lack Of Details> 

### ISSUE THREAD

**Issue by unknown918** [microsoft/graphrag#709]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I configured my yaml file with `max_tokens: 16000`, but the result is still relatively short(only hundreds of tokens) and lacks enough details(which is extremely rich in the txt file I gave to it. It can point out where those details are, but they were simply not in the response.

### GraphRAG Config Used

```yaml
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: key
  type: openai_chat # or azure_openai_chat
  model: Qwen/Qwen2-7B-Instruct
  model_supports_json: false # recommended if this is available for your model.
  max_tokens: 16000
  # request_timeout: 180.0
  api_base: http://localhost:8000/v1
```

### Additional Information

- GraphRAG Version:
- Operating System: 
- Python Version:
- Related Issues:
