### ISSUE TITLE
[Issue]: AttributeError: 'str' object has no attribute 'embedding'

### ISSUE THREAD

**Issue by wenmengzhou** [microsoft/graphrag#732]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

When use with self-host openAI embedding interface, run with following error:

```shell
372 Traceback (most recent call last):
373   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py", line 415, in _execute_verb
374     result = await result
375   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/index/verbs/text/embed/text_embed.py", line 105, in text_embed
376     return await _text_embed_in_memory(
377   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/index/verbs/text/embed/text_embed.py", line 130, in _text_embed_in_memory
378     result = await strategy_exec(texts, callbacks, cache, strategy_args)
379   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py", line 62, in run
380     embeddings = await _execute(llm, text_batches, ticker, semaphore)
381   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py", line 106, in _execute
382     results = await asyncio.gather(*futures)
383   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/index/verbs/text/embed/strategies/openai.py", line 100, in embed
384     chunk_embeddings = await llm(chunk)
385   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/caching_llm.py", line 104, in __call__
386     result = await self._delegate(input, **kwargs)
387   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/rate_limiting_llm.py", line 177, in __call__
388     result, start = await execute_with_retry()
389   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/rate_limiting_llm.py", line 159, in execute_with_retry
390     async for attempt in retryer:
391   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
392     do = await self.iter(retry_state=self._retry_state)
393   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
394     result = await action(retry_state)
395   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/tenacity/_utils.py", line 99, in inner
396     return call(*args, **kwargs)
397   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/tenacity/__init__.py", line 398, in <lambda>
398     self._add_action_func(lambda rs: rs.outcome.result())
399   File "/opt/anaconda3/envs/graphrag/lib/python3.10/concurrent/futures/_base.py", line 451, in result
400     return self.__get_result()
401   File "/opt/anaconda3/envs/graphrag/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
402     raise self._exception
403   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/rate_limiting_llm.py", line 165, in execute_with_retry
404     return await do_attempt(), start
405   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/rate_limiting_llm.py", line 147, in do_attempt
406     return await self._delegate(input, **kwargs)
407   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/base_llm.py", line 49, in __call__
408     return await self._invoke(input, **kwargs)
409   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/base/base_llm.py", line 53, in _invoke
410     output = await self._execute_llm(input, **kwargs)
411   File "/Users/zhouwenmeng/work/code/llm/application/graphrag/graphrag/llm/openai/openai_embeddings_llm.py", line 36, in _execute_llm
412     embedding = await self.client.embeddings.create(
413   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/resources/embeddings.py", line 215, in create
414     return await self._post(
415   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/_base_client.py", line 1826, in post
416     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
417   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/_base_client.py", line 1519, in request
418     return await self._request(
419   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/_base_client.py", line 1622, in _request
420     return await self._process_response(
421   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/_base_client.py", line 1714, in _process_response
422     return await api_response.parse()
423   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/_response.py", line 419, in parse
424     parsed = self._options.post_parser(parsed)
425   File "/opt/anaconda3/envs/graphrag/lib/python3.10/site-packages/openai/resources/embeddings.py", line 204, in parser
426     data = cast(object, embedding.embedding)
427 AttributeError: 'str' object has no attribute 'embedding'
```

### Steps to reproduce

following the quick start tutorial:
https://microsoft.github.io/graphrag/posts/get_started/

the config file is as follows:
```yaml

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key:  my-secret-key
  type: openai_chat # or azure_openai_chat
  #￥type: azure_openai_chat # or azure_openai_chat
  # model: gpt-4-turbo-preview
  model: qwen-plus
  model_supports_json: false # recommended if this is available for your model.
  # max_tokens: 4000
  request_timeout: 180.0
  api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
#  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  top_p: 0.99999999 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  num_threads: 1 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: eyJ0eXAiOiJqd3QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6IjMxNTEzMSIsInBhc3N3b3JkIjoiMzE1MTMxIiwiZXhwIjoyMDA1NjE0MzYxfQ.GdA72mKVMBS1Kj-HFV8o4gTxldjUAbooOX9aKszwIXs
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-small
    api_base: http://47.88.8.18:8088/v1
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional



chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: sk-72b9b57905b142e396722b0e01b982bf
  type: openai_chat # or azure_openai_chat
  #￥type: azure_openai_chat # or azure_openai_chat
  # model: gpt-4-turbo-preview
  model: qwen-plus
  model_supports_json: false # recommended if this is available for your model.
  # max_tokens: 4000
  request_timeout: 180.0
  api_base: https://dashscope.aliyuncs.com/compatible-mode/v1
#  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  top_p: 0.99999999 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  num_threads: 4 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key:  my-secret-key
    type: openai_embedding # or azure_openai_embedding
    model: text-embedding-3-small
    api_base: http://my-embedding-host/v1
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional



chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents

input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  llm_top_p: 0.999999 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  llm_top_p: 0.999999 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: false
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  llm_top_p: 0.999999 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  llm_top_p: 0.999999 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

```

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Logs and screenshots

❌ create_final_entities
None
⠹ GraphRAG Indexer
├── Loading Input (text) - 1 files loaded (0 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
└── create_final_entities
❌ Errors occurred during the pipeline run, see logs for more details.

_No response_

### Additional Information

- GraphRAG Version:  main brnach ac6f240e29c4f8356cf5e2727e2154f3fed8b1db
- Operating System:  macbook
- Python Version: py310
- Related Issues: None
