### ISSUE TITLE
[Bug]: create_final_community_reports fails for gpt-4

### ISSUE THREAD

**Issue by miaomiaocui** [microsoft/graphrag#745]
### Do you need to file an issue?

- [X] I have searched the existing issues and this bug is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate bug, not just a question. If this is a question, please use the Discussions area.

### Describe the bug

create_final_community_reports fails for `gpt-4`, but no issue with other OAI models such  as `gpt-4-turbo-preview` or `gpt-4o-mini`

### Steps to reproduce

change the model to `gpt-4` in settings.yaml, and run `python -m graphrag.index --root ./ragtest`

### Expected Behavior

❌ create_final_community_reports
None
⠹ GraphRAG Indexer
├── Loading Input (InputFileType.text) - 2 files loaded (1 filtered) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
├── create_final_entities
├── create_final_nodes
├── create_final_communities
├── join_text_units_to_entity_ids
├── create_final_relationships
├── join_text_units_to_relationship_ids
└── create_final_community_reports
❌ Errors occurred during the pipeline run, see logs for more details.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by minglong-huang** [comment]
我也是同样的问题 好烦呀 解决了好久还是不行

**Comment by xldistance** [comment]
There should be an error running your embedding model, check out my setup!
```
embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: asyncio # or asyncio
  llm:
    # api_key: sk-9mxwRPHwHt8M1ct7CaCf041d6fC44e9587A041Ca3145E09e
    # type: openai_embedding # or azure_openai_embedding
    # model: text-embedding-ada-002
    # api_base: https://apis.wumingai.com/v1
    api_key: xinference
    type: openai_embedding # or azure_openai_embedding
    model: bge-m3
    api_base: http://127.0.0.1:9997/v1
```
