### ISSUE TITLE
[Issue]: <title> Too many Request.

### ISSUE THREAD

**Issue by prasantpoudel** [microsoft/graphrag#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [ ] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

I am trying to index the 5 txt file using the groq model api.
{'error': {'message': 'Rate limit reached for model `llama3-8b-8192` in organization `org_01j3pzreckfdqazc407qtskwvq` on tokens per minute (TPM): Limit 30000, Used 73124, Requested 1877. Please try again in 1m30.002s.

my config:
```
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GROQ_API_KEY} # groq api key
  type: openai_chat # or azure_openai_chat
  model: llama3-8b-8192
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 4000
  # request_timeout: 180.0
  api_base: https://api.groq.com/openai/v1
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  tokens_per_minute: 25000 # set a leaky bucket throttle
  requests_per_minute: 1 # set a leaky bucket throttle
  max_retries: 3
  # max_retry_wait: 10000.0
  sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
```
which parameter should i need to change to get rid of this error.

### GraphRAG Config Used

```yaml
# Paste your config here

```

### Additional Information

- GraphRAG Version:
- Operating System:
- Python Version:
- Related Issues:

**Comment by natoverse** [comment]
Routing to #657 - this question has come up in various forms, but it is hard for us to diagnose directly since the model provider may not have the same response details that we use to track request and token consumption. See #616 for example.

**Comment by prasantpoudel** [comment]
Able to rectify this problem by following code:

```
encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GROQ_API_KEY} # groq api key
  type: openai_chat # or azure_openai_chat
  model: llama3-8b-8192
  model_supports_json: true # recommended if this is available for your model.
  max_tokens: 4000
  # request_timeout: 180.0
  api_base: https://api.groq.com/openai/v1
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  tokens_per_minute: 2000 # set a leaky bucket throttle
  requests_per_minute: 1 # set a leaky bucket throttle
  max_retries: 3
  # max_retry_wait: 10000.0
  sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  concurrent_requests: 1 # the number of parallel inflight requests that may be made / default is 25 / reduce if using the groq

parallelization:
  stagger: 0.1
  num_threads: 2 # the number of threads to use for parallel processing (make it low, if you are using Groq api for multiple file indexing)
```
