### ISSUE TITLE
Support loading from storage blob in query library

### ISSUE THREAD

**Issue by natoverse** [microsoft/graphrag#799]
### Do you need to file an issue?

- [X] I have searched the existing issues and this feature is not already filed.
- [X] My model is hosted on OpenAI or Azure. If not, please look at the "model providers" issue and don't file a new one here.
- [X] I believe this is a legitimate feature request, not just a question. If this is a question, please use the Discussions area.

### Is your feature request related to a problem? Please describe.

We have received reports of issues with blob storage (for example https://github.com/microsoft/graphrag/issues/789). It turns out that we had not yet migrated the blob loading used by the indexer into the query portion at all, so this just fails. Filing this as a "missing feature".

**Comment by nociza** [comment]
Hi can you provide an example of how we can configure settings.yaml so that it can access the output folder on Azure Blob Storage? Here's my current version:

```
storage:
  type: blob
  base_dir: "output/${timestamp}/artifacts"
  connection_string: "DefaultEndpointsProtocol=https;AccountName=<my account name>;AccountKey=<my account key>;EndpointSuffix=core.windows.net"
  container_name: "data"
 ```
 
 But I'm getting "Parent directory output does not exist or is not a directory." error. 
 
 After digging into it a bit, the error seems to be arising from the resolve path function where it can't use the blob path directl y and thinks the directory doesn't exist.
