### ISSUE TITLE
[Issue]: <title> ERROR error generating community report

### ISSUE THREAD

**Issue by n0123ab** [microsoft/graphrag#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues
- [X] I have checked [#657](https://github.com/microsoft/graphrag/issues/657) to validate if my issue is covered by community support

### Describe the issue

When generating community_reports it just shows error, it seem like some errors on json? 
I was tried #772 solution but it is not wokring on my desktop and changed model_supports_json: true from true to false. it also not work.

the llm model is from ollama
the embeddings model is from xinference

### Steps to reproduce

🚀 Reading settings from ragtest/settings.yaml
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
🚀 create_base_text_units
                                  id  ... n_tokens
0   1deea9b3aeb4529df57728a72417237d  ...     1200
1   4d1761f41aa825a6417d33552ef73529  ...     1200
2   97b4d69360a070ff501e3d7094acf40f  ...     1200
3   cfbb152ad20108f6f58cfa90af159af9  ...     1200
4   df6f974f9acf69c0bafd15380675749e  ...     1200
5   a97140c6424e74226e5ebd23e53160c4  ...     1200
6   3819b16dae74480c7ec3ce53bc8991d0  ...     1200
7   52ae7c86022db4776478eb43aa539b03  ...     1200
8   1616eba3f8622b53a008bf849ddb4a54  ...     1200
9   d8368121eff28a357b7e912aab1884c6  ...     1200
10  9594e43f483ac153d505ccede24f1f4d  ...     1200
11  ad9fdb9694ea81cc940f0e612898d06b  ...     1200
12  6d13e94314df51b7fdabfe3d336e3d31  ...     1200
13  7244b563fbccd65c898abb0bb8f597e0  ...     1200
14  33337490d8b278c9858195fb30091d09  ...     1200
15  f5d314ff303d1a66ba9c694769d73a35  ...     1200
16  4460d651dd1c95fff3379d1425c81b00  ...     1200
17  7f39647bd9c095d0d3a62f410f83723c  ...     1200
18  2ce7b25ada84e2226875b97edece0c7d  ...     1200
19  819e13a7bc211f07e3d3ce0eb63a18ac  ...     1200
20  32d7318349fad1e1bbb142e0731ec319  ...     1200
21  9d754a400f1eec5864314616b57bf489  ...     1200
22  2e4cd4170a12f9768f298ff99d804410  ...     1200
23  1a81298f81d9721c9cf5d252a2f80f51  ...     1200
24  047c60953620c0bba26cf0b662d050fc  ...     1200
25  51034a0b4a725ffedf938732ecd31fc9  ...     1012

[26 rows x 5 columns]
🚀 create_base_extracted_entities
                                        entity_graph
0  <graphml xmlns="http://graphml.graphdrawing.or...
🚀 create_summarized_entities
                                        entity_graph
0  <graphml xmlns="http://graphml.graphdrawing.or...
🚀 create_base_entity_graph
   level                                    clustered_graph
0      0  <graphml xmlns="http://graphml.graphdrawing.or...
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
🚀 create_final_entities
                                 id  ...                      
description_embedding
0  b45241d70f0e43fca764df95b2b81f77  ...  
[-0.0066836378537118435, -0.028212515637278557...
1  4119fd06010c494caa07f439b333f4c5  ...  
[-0.08931764960289001, 0.03248097002506256, -0...

[2 rows x 8 columns]
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/dat
ashaper/engine/verbs/convert.py:72: FutureWarning: 
errors='ignore' is deprecated and will raise in a future 
version. Use to_datetime without passing `errors` and catch 
exceptions explicitly instead
  datetime_column = pd.to_datetime(column, errors="ignore")
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/dat
ashaper/engine/verbs/convert.py:72: UserWarning: Could not 
infer format, so each element will be parsed individually, 
falling back to `dateutil`. To ensure parsing is consistent 
and as-expected, please specify a format.
  datetime_column = pd.to_datetime(column, errors="ignore")
🚀 create_final_nodes
   level          title  ...  x  y
0      0  SAMUEL NAMARA  ...  0  0
1      0      FIRUZABAD  ...  0  0

[2 rows x 14 columns]
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
🚀 create_final_communities
  id  ...                       text_unit_ids
0  0  ...  

[1 rows x 6 columns]
🚀 join_text_units_to_entity_ids
                      text_unit_ids  ...                      
id
0  d8368121eff28a357b7e912aab1884c6  ...  
d8368121eff28a357b7e912aab1884c6

[1 rows x 3 columns]
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/num
py/core/fromnumeric.py:59: FutureWarning: 'DataFrame.swapaxes'
is deprecated and will be removed in a future version. Please 
use 'DataFrame.transpose' instead.
  return bound(*args, **kwds)
/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/dat
ashaper/engine/verbs/convert.py:65: FutureWarning: 
errors='ignore' is deprecated and will raise in a future 
version. Use to_numeric without passing `errors` and catch 
exceptions explicitly instead
  column_numeric = cast(pd.Series, pd.to_numeric(column, 
errors="ignore"))
🚀 create_final_relationships
          source     target  ...  target_degree rank
0  SAMUEL NAMARA  FIRUZABAD  ...              1    2

[1 rows x 10 columns]
🚀 join_text_units_to_relationship_ids
                                 id                    
relationship_ids
0  d8368121eff28a357b7e912aab1884c6  
❌ create_final_community_reports
None
⠏ GraphRAG Indexer 
├── Loading Input (InputFileType.text) - 1 files loaded (0… … 
├── create_base_text_units
├── create_base_extracted_entities
├── create_summarized_entities
├── create_base_entity_graph
├── create_final_entities
├── create_final_nodes
├── create_final_communities
├── join_text_units_to_entity_ids
├── create_final_relationships
├── join_text_units_to_relationship_ids
└── create_final_community_reports
❌ Errors occurred during the pipeline run, see logs for more 
details.

### GraphRAG Config Used

```yaml

encoding_model: cl100k_base
skip_workflows: []
llm:
  api_key: ${GRAPHRAG_API_KEY}
  type: openai_chat # or azure_openai_chat
  model: qwen2:0.5b
  model_supports_json: false # recommended if this is available for your model.
  # max_tokens: 4000
  # request_timeout: 180.0
  api_base: http://127.0.0.1:11434/v1
  # api_version: 2024-02-15-preview
  # organization: <organization_id>
  # deployment_name: <azure_model_deployment_name>
  # tokens_per_minute: 150_000 # set a leaky bucket throttle
  # requests_per_minute: 10_000 # set a leaky bucket throttle
  # max_retries: 10
  # max_retry_wait: 10.0
  # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
  # concurrent_requests: 25 # the number of parallel inflight requests that may be made
  # temperature: 0 # temperature for sampling
  # top_p: 1 # top-p sampling
  # n: 1 # Number of completions to generate

parallelization:
  stagger: 0.3
  # num_threads: 50 # the number of threads to use for parallel processing

async_mode: threaded # or asyncio

embeddings:
  ## parallelization: override the global parallelization settings for embeddings
  async_mode: threaded # or asyncio
  llm:
    api_key: ${GRAPHRAG_API_KEY}
    type: openai_embedding # or azure_openai_embedding
    model: bge-base-zh-v1.5
    api_base: http://0.0.0.0:9997/v1
    # api_version: 2024-02-15-preview
    # organization: <organization_id>
    # deployment_name: <azure_model_deployment_name>
    # tokens_per_minute: 150_000 # set a leaky bucket throttle
    # requests_per_minute: 10_000 # set a leaky bucket throttle
    # max_retries: 10
    # max_retry_wait: 10.0
    # sleep_on_rate_limit_recommendation: true # whether to sleep when azure suggests wait-times
    # concurrent_requests: 25 # the number of parallel inflight requests that may be made
    # batch_size: 16 # the number of documents to send in a single request
    # batch_max_tokens: 8191 # the maximum number of tokens to send in a single request
    # target: required # or optional
  


chunks:
  size: 1200
  overlap: 100
  group_by_columns: [id] # by default, we don't allow chunks to cross documents
    
input:
  type: file # or blob
  file_type: text # or csv
  base_dir: "input"
  file_encoding: utf-8
  file_pattern: ".*\\.txt$"

cache:
  type: file # or blob
  base_dir: "cache"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

storage:
  type: file # or blob
  base_dir: "output/${timestamp}/artifacts"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

reporting:
  type: file # or console, blob
  base_dir: "output/${timestamp}/reports"
  # connection_string: <azure_blob_storage_connection_string>
  # container_name: <azure_blob_storage_container_name>

entity_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/entity_extraction.txt"
  entity_types: [organization,person,geo,event]
  max_gleanings: 1

summarize_descriptions:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/summarize_descriptions.txt"
  max_length: 500

claim_extraction:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  # enabled: true
  prompt: "prompts/claim_extraction.txt"
  description: "Any claims or facts that could be relevant to information discovery."
  max_gleanings: 1

community_reports:
  ## llm: override the global llm settings for this task
  ## parallelization: override the global parallelization settings for this task
  ## async_mode: override the global async_mode settings for this task
  prompt: "prompts/community_report.txt"
  max_length: 2000
  max_input_length: 8000

cluster_graph:
  max_cluster_size: 10

embed_graph:
  enabled: false # if true, will generate node2vec embeddings for nodes
  # num_walks: 10
  # walk_length: 40
  # window_size: 2
  # iterations: 3
  # random_seed: 597832

umap:
  enabled: false # if true, will generate UMAP embeddings for nodes

snapshots:
  graphml: true
  raw_entities: false
  top_level_nodes: false

local_search:
  # text_unit_prop: 0.5
  # community_prop: 0.1
  # conversation_history_max_turns: 5
  # top_k_mapped_entities: 10
  # top_k_relationships: 10
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000

global_search:
  # llm_temperature: 0 # temperature for sampling
  # llm_top_p: 1 # top-p sampling
  # llm_n: 1 # Number of completions to generate
  # max_tokens: 12000
  # data_max_tokens: 12000
  # map_max_tokens: 1000
  # reduce_max_tokens: 2000
  # concurrency: 32

```

### Logs and screenshots

14:11:13,922 graphrag.index.graph.extractors.community_reports.community_reports_extractor ERROR error generating community report
Traceback (most recent call last):
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/index/graph/extractors/community_reports/community_reports_extractor.py", line 58, in __call__
    await self._llm(
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/openai/json_parsing_llm.py", line 34, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/openai/openai_token_replacing_llm.py", line 37, in __call__
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/openai/openai_history_tracking_llm.py", line 33, in __call__
    output = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/caching_llm.py", line 96, in __call__
    result = await self._delegate(input, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py", line 177, in __call__
    result, start = await execute_with_retry()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py", line 159, in execute_with_retry
    async for attempt in retryer:
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    do = await self.iter(retry_state=self._retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    result = await action(retry_state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/tenacity/_utils.py", line 99, in inner
    return call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/tenacity/__init__.py", line 398, in <lambda>
    self._add_action_func(lambda rs: rs.outcome.result())
                                     ^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py", line 165, in execute_with_retry
    return await do_attempt(), start
           ^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/rate_limiting_llm.py", line 147, in do_attempt
    return await self._delegate(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/base/base_llm.py", line 48, in __call__
    return await self._invoke_json(input, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/llm/openai/openai_chat_llm.py", line 88, in _invoke_json
    raise RuntimeError(FAILED_TO_CREATE_JSON_ERROR)
RuntimeError: Failed to generate valid JSON output
14:11:13,923 graphrag.index.reporting.file_workflow_callbacks INFO Community Report Extraction Error details=None
14:11:13,923 graphrag.index.verbs.graph.report.strategies.graph_intelligence.run_graph_intelligence WARNING No report found for community: 0
14:11:13,948 datashaper.workflow.workflow INFO executing verb window
14:11:13,948 datashaper.workflow.workflow ERROR Error executing verb "window" in create_final_community_reports: 'community'
Traceback (most recent call last):
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
                                                     ~~~~~~~~~~~^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
14:11:13,950 graphrag.index.reporting.file_workflow_callbacks INFO Error executing verb "window" in create_final_community_reports: 'community' details=None
14:11:13,950 graphrag.index.run ERROR error running workflow create_final_community_reports
Traceback (most recent call last):
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/graphrag/index/run.py", line 323, in run_pipeline
    result = await workflow.run(context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 369, in run
    timing = await self._execute_verb(node, context, callbacks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/datashaper/workflow/workflow.py", line 410, in _execute_verb
    result = node.verb.func(**verb_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/datashaper/engine/verbs/window.py", line 73, in window
    window = __window_function_map[window_operation](input_table[column])
                                                     ~~~~~~~~~~~^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/pandas/core/frame.py", line 4102, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/karl/anaconda3/envs/Rag/lib/python3.11/site-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'community'
14:11:13,950 graphrag.index.reporting.file_workflow_callbacks INFO Error running pipeline! details=None


### Additional Information

- GraphRAG Version:0.2.2
- Operating System: ubuntu22.04
- Python Version:3.11.9
- Related Issues:error when executing verb create_community_reports
